---
- name: Deploy www.diversionforum.net
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: no

  vars:
    app: "www.diversionforum.net"
    container: "www.diversionforum.net"
    root: '/home/poduser/code/'
    repo: 'git@github.com:eingram23/'
    mysql_root: "{{ lookup('hashi_vault','secret=secret/data/dfprod/mysql:root') }}"
    mysql_smfprod: "{{ lookup('hashi_vault','secret=secret/data/dfprod/mysql:smfprod') }}"
    nginx_port: "8080"

  roles:
    - role: common
      become_user: poduser
      become_method: sudo
    - role: set_perms
      become: true
      become_method: sudo

  