---
- name: Create nut-upsd conf folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/nut-upsd

- name: Copy shutdown script to host
  ansible.builtin.copy:
    src: shutdown.yaml
    dest: /opt/nut-upsd/shutdown.yaml
    mode: '0644'

- name: Copy upssched-cmd to host
  ansible.builtin.copy:
    src: upssched-cmd
    dest: /opt/nut-upsd/upssched-cmd
    mode: '0644'

- name: Start docker container
  community.docker.docker_container:
    name: homelab-nut-upsd
    image: homelab-nut-upsd:latest
    env:
      API_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
      # PORT: '/dev/usb/hiddev0'
    ports:
      - "3493:3493/tcp"
    volumes:
      - /opt/nut-upsd/upssched-cmd:/usr/bin/upssched-cmd
      - /opt/nut-upsd/shutdown.yaml:/etc/nut/shutdown.yaml
    privileged: true
    restart_policy: always
