- name: Create vault pod
  containers.podman.podman_pod:
    name: vault
    state: started
    publish: 
      - 8200:8200/tcp

- name: Create vault-dev-server container
  containers.podman.podman_container:
    name: vault-dev-server
    image: vault:1.11.0
    state: started
    restart_policy: always
    pod: vault
    env:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "dev-token"
    cap_add:
      - IPC_LOCK
  