---
- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.linux.firewall
    apply:
      become: true
      become_method: sudo
      become_user: root

- name: Create influxdb folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: poduser
    group: poduser
    recurse: true
  loop:
    - /opt/influxdb
  become: true
  become_method: sudo
  become_user: root

- name: Run podman unshare
  ansible.builtin.shell:
    podman unshare chown -R 1000:1000 /opt/influxdb

- name: Create influxdb container
  containers.podman.podman_container:
    name: influxdb
    image: docker.io/influxdb:{{ influxdb_ver }}
    state: stopped
    restart_policy: unless-stopped
    env:
      DOCKER_INFLUXDB_INIT_MODE=setup
      DOCKER_INFLUXDB_INIT_USERNAME=admin
      DOCKER_INFLUXDB_INIT_PASSWORD={{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}
      DOCKER_INFLUXDB_INIT_ORG=Homelab
      DOCKER_INFLUXDB_INIT_BUCKET=HA
    publish:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - /opt/influxdb:/etc/influxdb2:z
    generate_systemd:
      path: /home/poduser/.config/systemd/user
      restart_policy: always

- name: Set XDG_RUNTIME_DIR env variable
  ansible.builtin.lineinfile:
    path: /home/poduser/.bash_profile
    search_string: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'
    insertafter: '# User specific environment and startup programs'
    line: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'

- name: Get poduser info
  ansible.builtin.user:
    name: poduser
  register: poduser_info

- name: Generate systemd units for influxdb container
  containers.podman.podman_generate_systemd:
    name: influxdb
    no_header: true
    restart_policy: always
    dest: ~/.config/systemd/user/

- name: Enable and start container-influxdb service
  ansible.builtin.systemd:
    name: container-influxdb
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ poduser_info.uid }}