- name: Assert that app and bucket are set
  ansible.builtin.assert:
    that:
      - app is defined
      - port is defined
    fail_msg: "app, bucket and port (8086+) are required"

- name: Set app_name
  ansible.builtin.set_fact:
    app_name: "{{ app }}-{{ app_suffix }}"

- name: Set fw_port
  ansible.builtin.set_fact:
    fw_port:
      - "{{ port }}/tcp"
    publish_port:
      - "{{ port }}:8086"

- name: Uninstall {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: remove_all
