---
- name: Create and run grafana container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: grafana/grafana:{{ ver }}
    state: started
    restart_policy: always
    pod: "{{ pod_name }}"
    volume:
      - "{{ container_name }}_config:/etc/grafana"
      - "{{ container_name }}_data:/var/lib/grafana"
