---
- name: Create grafana folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: poduser
    group: poduser
  loop:
    - /opt/grafana
    - /opt/grafana/dashboards
    - /opt/grafana/dashboardfiles
    - /opt/grafana/datasources
  become: true
  become_method: sudo
  become_user: root

- name: Copy grafana dashboard provisioning file to remote server
  ansible.builtin.copy:
    src: dashboards.yaml
    dest: /opt/grafana/dashboards
    mode: '0644'
    owner: poduser
    group: poduser

- name: Copy grafana dashboards to remote server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/grafana/dashboardfiles
    mode: '0644'
    owner: poduser
    group: poduser
  with_fileglob: "{{ role_path }}/files/dashboards/*"

- name: Create grafana datasource provisioning file on remote server
  ansible.builtin.template:
    src: datasources.yaml.j2
    dest: /opt/grafana/datasources/datasources.yaml
    mode: '0644'
    owner: poduser
    group: poduser

- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.homelab.firewall
    apply:
      become: true
      become_method: sudo
      become_user: root

- name: Create and run grafana container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/grafana/grafana:{{ ver }}
    state: started
    restart_policy: always
    pod: "{{ pod_name }}"
    volume:
      - "{{ container_name }}_config:/etc/grafana"
      - "{{ container_name }}_data:/var/lib/grafana"
      - "/opt/grafana/dashboards:/etc/grafana/provisioning/dashboards"
      - "/opt/grafana/dashboardfiles:/var/lib/grafana/dashboards"
      - "/opt/grafana/datasources:/etc/grafana/provisioning/datasources"
