---
- name: Run root tasks
  become: true
  become_method: sudo
  become_user: root
  block:
    - name: Enable linger for {{ user_account }} user
      ansible.builtin.command: loginctl enable-linger {{ user_account }}

    - name: Open firewall port
      ansible.builtin.include_role:
        name: eingram23.linux.firewall

    - name: Create {{ app_name }} root folder
      ansible.builtin.file:
        path: /opt/{{ app_name }}
        state: directory
        mode: '0755'
        owner: poduser
        group: poduser

    - name: Create {{ app_name }} dashboards folder
      ansible.builtin.file:
        path: /opt/{{ app_name }}/dashboards
        state: directory
        mode: '0755'
        owner: poduser
        group: poduser

    - name: Create {{ app_name }} datasources folder
      ansible.builtin.file:
        path: /opt/{{ app_name }}/datasources
        state: directory
        mode: '0755'
        owner: poduser
        group: poduser

- name: Copy grafana dashboard json files to remote server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/{{ app_name }}/dashboards/
    mode: '0644'
    owner: poduser
    group: poduser
  with_fileglob: "*.json"

- name: Copy grafana dashboard config to remote server
  ansible.builtin.copy:
    src: dashboards.yaml
    dest: /opt/{{ app_name }}/dashboards/
    mode: '0644'
    owner: poduser
    group: poduser

- name: Create grafana datasource config on remote server
  ansible.builtin.template:
    src: datasources.yaml.j2
    dest: /opt/{{ app_name }}/datasources/datasources.yaml
    owner: poduser
    group: poduser

- name: Prep for upgrade
  when: upgrade == "yes"
  block:
    # - name: Stop systemd service for {{ app_name }} container
    #   ansible.builtin.systemd:
    #     name: container-{{ app_name }}
    #     state: stopped
    #     scope: user

    - name: Remove {{ app_name }} container
      containers.podman.podman_container:
        name: "{{ app_name }}"
        state: absent

    - name: Cleanup old image
      containers.podman.podman_image:
        name: "{{ image }}:{{ old_ver }}"
        state: absent

- name: Create and run {{ app_name }} container
  containers.podman.podman_container:
    name: "{{ app_name }}"
    image: "{{ image }}:{{ ver }}"
    state: stopped
    restart_policy: always
    user: 472
    pod: "{{ pod_name }}"
    # publish:
    #   - "3000:3000"
    env:
      GF_INSTALL_PLUGINS: "grafana-clock-panel, flant-statusmap-panel, marcusolsson-treemap-panel"
    volume:
      - /opt/{{ app_name }}/dashboards:/etc/grafana/provisioning/dashboards
      - /opt/{{ app_name }}/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    # generate_systemd:
    #   path: /home/{{ user_account }}/.config/systemd/user
    #   restart_policy: always

# - name: Set XDG_RUNTIME_DIR env variable
#   ansible.builtin.lineinfile:
#     path: /home/{{ user_account }}/.bash_profile
#     search_string: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'
#     insertafter: '# User specific environment and startup programs'
#     line: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'

# - name: Get {{ user_account }} info
#   ansible.builtin.user:
#     name: "{{ user_account }}"
#   register: user_info

# - name: Enable container-{{ app_name }} service
#   ansible.builtin.systemd:
#     name: container-{{ app_name }}
#     state: started
#     enabled: true
#     daemon_reload: true
#     scope: user
#   environment:
#     XDG_RUNTIME_DIR: /run/user/{{ user_info.uid }}
