- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Create folders for {{ app_name }}
      ansible.builtin.file:
        path: "{{ folder_item }}"
        state: directory
      loop:
        - /opt/{{ app_name }}/dashboards
        - /opt/{{ app_name }}/datasources
      loop_control:
        loop_var: folder_item

    - name: Create github key
      ansible.builtin.template:
        src: ssh-key-git.key.j2
        dest: /var/tmp/ssh-key-git.key
        mode: '0400'

    - name: Pull down configs repo from git
      ansible.builtin.git:
        repo: 'git@github.com:eingram23/configs.git'
        dest: /var/tmp/configs
        key_file: /var/tmp/ssh-key-git.key
        accept_hostkey: true
        force: true

    - name: Delete github key
      ansible.builtin.file:
        path: /var/tmp/ssh-key-git.key
        state: absent

    - name: Register dashboard file names
      ansible.builtin.find:
        paths: /var/tmp/configs/grafana/dashboards
        recurse: false
        patterns: "*.json"
      register: files_to_copy

    - name: Copy grafana dashboard json files to remote server
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /opt/{{ app_name }}/dashboards/
        mode: '0644'
        remote_src: true
      with_items: "{{ files_to_copy.files }}"

    - name: Remove configs repo
      ansible.builtin.file:
        path: /var/tmp/configs
        state: absent

    - name: Copy grafana config to remote server
      ansible.builtin.copy:
        src: dashboards.yaml
        dest: /opt/{{ app_name }}/dashboards/
        mode: '0644'

    - name: Create grafana datasource config on remote server
      ansible.builtin.template:
        src: datasources.yaml.j2
        dest: /opt/{{ app_name }}/datasources/datasources.yaml
        mode: '0644'

    - name: Restart service container-{{ app_name }}
      ansible.builtin.systemd:
        name: container-{{ app_name }}
        state: restarted
        scope: "{{ 'user' if user_account != 'root' else 'system' }}"
        enabled: true
        daemon_reload: true
