---
app_name: "portainer_agent"
image: "docker.io/portainer/agent"
upgrade: "no"
fw_port:
  - "9001/tcp"
mode: "rootful"
portainer_url: "http://portainer.local.lan:9000"
# agent_endpoint: "tcp://podhost-dev.local.lan:9002"
publish_port:
  - "9001:9001"
# user_account: "poduser"

