---
- name: Deploy alertmanager container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: poduser

  tasks:

    - name: Run alertmanager role
      ansible.builtin.include_role:
        name: eingram23.containers.alertmanager
