---
- name: Deploy dbeaver container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: poduser

  tasks:

    - name: Create dbeaver container
      when: task == "install"
      ansible.builtin.include_role:
        name: eingram23.containers.dbeaver
        tasks_from: install

    - name: Create dbeaver container
      when: task == "uninstall"
      ansible.builtin.include_role:
        name: eingram23.containers.dbeaver
        tasks_from: uninstall
