---
- name: Deploy grafana_alloy container
  hosts: "{{ hostvar | default([]) }}"
  become: false

  tasks:

    - name: Deploy grafana alloy - {{ task }}
      when: ansible_distribution in ['Debian', 'Ubuntu']
      become: true
      become_method: sudo
      ansible.builtin.import_role:
        name: eingram23.containers.grafana_alloy_docker
        tasks_from: "{{ task }}"

    - name: Deploy grafana alloy - {{ task }}
      when: ansible_distribution in ['Redhat', 'Rocky']
      ansible.builtin.import_role:
        name: eingram23.containers.grafana_alloy
        tasks_from: "{{ task }}"