---
# NEEDED VARS: hostvar
- name: Deploy grafana_alloy container
  hosts: "{{ hostvar | default([]) }}"
  become: false

  tasks:

    # - name: Migrate from node-exporter/promtail
    #   when: migrate == "yes"
    #   ansible.builtin.import_role:
    #     name: eingram23.containers.grafana_alloy
    #     tasks_from: migrate

    - name: Deploy grafana_alloy container
      ansible.builtin.import_role:
        name: eingram23.containers.grafana_alloy
        tasks_from: "{{ task }}"