---
- name: Deploy monitoring pod and containers
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: poduser

  # vars:
  #   pod_name: "monitoring"
  #   publish_ports:
  #     - "9090:9090"
  #     - "9093:9093"
  #     - "3000:3000"
  #     - "9272:9272"
  #     - "9115:9115"
  #     - "3100:3100"
  #     - "9116:9116"
  #     - "116:116/udp"
  #     - "514:514"
  #     - "514:514/udp"

  tasks:

    - name: Create prometheus container
      ansible.builtin.import_role:
        name: eingram23.containers.prometheus

    - name: Create grafana container
      ansible.builtin.import_role:
        name: eingram23.containers.grafana

    - name: Create vmware_exporter container
      ansible.builtin.import_role:
        name: eingram23.containers.vmware_exporter

    - name: Create alertmanager container
      ansible.builtin.import_role:
        name: eingram23.containers.alertmanager

    - name: Create loki container
      ansible.builtin.import_role:
        name: eingram23.containers.loki

    - name: Create blackbox_exporter container
      ansible.builtin.import_role:
        name: eingram23.containers.blackbox_exporter

    - name: Create snmp_exporter container
      ansible.builtin.import_role:
        name: eingram23.containers.snmp_exporter

    - name: Create unpoller container
      ansible.builtin.import_role:
        name: eingram23.containers.unpoller

    - name: Create rsyslog container
      ansible.builtin.import_role:
        name: eingram23.containers.rsyslog

    - name: Create promtail_syslog container
      ansible.builtin.import_role:
        name: eingram23.containers.promtail_syslog
