---
- name: Deploy plex_srv container
  hosts: "{{ hostvar | default('homenas.local.lan') }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: shareaccess

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.containers.plex_srv
