---
- name: Create postgres and dbeaver containers
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: poduser

  tasks:

    # - name: Create postgres container
    #   ansible.builtin.include_role:
    #     name: eingram23.containers.postgres

    - name: Create dbeaver container
      ansible.builtin.include_role:
        name: eingram23.containers.dbeaver

    # - name: Install software req
    #   ansible.builtin.dnf:
    #     name: "{{ package_item }}"
    #     state: present
    #     disable_gpg_check: true
    #   loop:
    #     - 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    #     - python3-psycopg2
    #   loop_control:
    #     loop_var: package_item

    # - name: Disable default postgresql repo
    #   command: dnf -qy module disable postgresql

    # - name: Install postgresql
    #   ansible.builtin.dnf:
    #     name: postgresql13
    #     state: present

