---
- name: Deploy postgres container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: false

  tasks:

    - name: Create postgres container
      ansible.builtin.import_role:
        name: eingram23.containers.postgres
        tasks_from: "{{ task }}"
      become: true
      become_method: sudo
      become_user: "{{ user_account }}"
