---
- name: Deploy prometheus container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: false

  tasks:

    - name: Run prometheus role
      ansible.builtin.import_role:
        name: eingram23.containers.prometheus
        tasks_from: "{{ task }}"