---
- name: Deploy snmp_exporter container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: poduser

  tasks:

    - name: Run snmp_exporter role
      ansible.builtin.include_role:
        name: eingram23.containers.snmp_exporter
