---
- name: Create grafana_agent folder structure
  ansible.builtin.file:
    path: /opt/grafana_agent
    state: directory
    mode: '0755'

- name: Make sure podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Install podman-plugins
  ansible.builtin.package:
    name: podman-plugins
    state: present

- name: Enable persistent storage for journalctl
  ansible.builtin.file:
    path: /var/log/journal
    state: directory
    mode: '0644'

- name: Create agent.yaml on remote server
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /opt/grafana_agent/{{ item }}
    mode: '0644'
  loop:
    - agent.yaml
  # notify: Restart grafana_agent container

- name: Run grafana_agent container
  containers.podman.podman_container:
    name: grafana_agent
    image: docker.io/grafana/agent:{{ ver }}
    state: stopped
    restart_policy: always
    privileged: true
    network: host
    pid: host
    cap_add:
      - SYS_TIME
    command: >
      --config.file=/etc/agent-config/agent.yaml
    volume:
      - /:/host/root:ro,rslave
      - /sys:/host/sys:ro,rslave
      - /proc:/host/proc:ro,rslave
      - /var/log:/var/log:ro
      - /opt/grafana_agent:/etc/agent
      - /opt/grafana_agent/agent.yaml:/etc/agent-config/agent.yaml
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:rw
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always

- name: Enable container-grafana_agent service
  ansible.builtin.systemd:
    name: container-grafana_agent
    state: started
    enabled: true
    daemon_reload: true
