---
- name: Create grafana_agent folder
  ansible.builtin.file:
    path: /opt/grafana_agent
    state: directory
    mode: '0755'

- name: Copy agent.yaml to remote server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/grafana_agent/
    mode: '0644'
  with_fileglob: "*"
  notify: Restart grafana_agent container

- name: Run grafana_agent container
  containers.podman.podman_container:
    name: grafana_agent
    image: grafana/agent:{{ ver }}
    state: stopped
    restart_policy: always
    privileged: true
    network: host
    pid: host
    command: >
      --net="host"
      --pid="host"
      --cap-add=SYS_TIME
      --config.file=/etc/agent-config/agent.yaml
    volume:
      - /:/host/root:ro,rslave
      - /sys:/host/sys:ro,rslave
      - /proc:/host/proc:ro,rslave
      - /tmp/agent:/etc/agent
      - /opt/grafana_agent/agent.yaml:/etc/agent-config/agent.yaml
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:rw
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always

- name: Get poduser info
  ansible.builtin.user:
    name: poduser
  register: poduser_info

- name: Enable container-grafana_agent service
  ansible.builtin.systemd:
    name: container-grafana_agent
    state: started
    enabled: true
    daemon_reload: true

