---
- block:
    - name: Stop container-node-exporter
      ansible.builtin.systemd:
        name: container-node-exporter
        state: stopped
        enabled: false
        scope: user

    - name: Remove node-exporter container
      containers.podman.podman_container:
        name: node-exporter
        state: absent

    - name: Run podman system prune
      ansible.builtin.shell: >
        echo y | podman system prune

    - name: Delete dangling podman images
      ansible.builtin.shell: podman image rm -a
  become: true
  become_method: sudo
  become_user: poduser

- name: Stop container-promtail
  ansible.builtin.systemd:
    name: container-promtail
    state: stopped
    enabled: false

- name: Remove promtail container
  containers.podman.podman_container:
    name: promtail
    state: absent

- name: Run podman system prune
  ansible.builtin.shell: |
    echo y | podman system prune

- name: Delete dangling podman images
  ansible.builtin.shell: podman image rm -a