---
- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Copy data-sources.json file
      ansible.builtin.copy:
        src: data-sources.json
        dest: /opt/{{ app_name }}/data-sources.json
        mode: '0644'
        owner: "{{ user_account }}"
        group: "{{ user_account }}"

    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    - name: Pull dbeaver image and start container
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: docker.io/dbeaver/cloudbeaver:{{ ver }}
        network: host
        env:
          CB_SERVER_NAME: "dbeaver"
          CB_ADMIN_NAME: "cbadmin"
          CB_ADMIN_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
          CB_SERVER_URL: http://{{ inventory_hostname }}:8978/
        volume:
          - "{{ app_name }}-data:/opt/dbeaver"
          - "/opt/{{ app_name }}/data-sources.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json"
        state: stopped
        restart_policy: always
        publish: "{{ publish_port }}"
        generate_systemd:
          path: "{{ '/home/' + user_account + '/.config/systemd/user' if user_account != 'root' else '/etc/systemd/system' }}"
          restart_policy: always

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd
