- name: Stop systemd service for container - {{ app_name }}
  ansible.builtin.systemd:
    name: container-{{ app_name }}
    scope: user
    state: stopped

- name: Remove container - {{ app_name }}
  containers.podman.podman_container:
    name: "{{ app_name }}"
    state: absent

- name: Cleanup image
  containers.podman.podman_image:
    name: "{{ image }}:{{ ver }}"
    state: absent

- name: Remove container - {{ app_name }}
  containers.podman.podman_container:
    name: "{{ app_name }}"
    state: absent

- name: Remove volumes for {{ app_name }}
  containers.podman.podman_volume:
    name: "{{ app_name }}_data"
    state: absent

- name: Disable service - container-{{ app_name }}
  ansible.builtin.systemd:
    name: container-{{ app_name }}
    state: stopped
    scope: user
    enabled: false
    daemon_reload: true

- name: Delete firewall rules
  become: true
  become_method: sudo
  become_user: root
  block:
    - name: Delete firewall rules
      ansible.builtin.include_role:
        name: eingram23.linux.firewall
        tasks_from: delete
