---
app_name: "snmp-exporter"
user_account: "poduser"
image_name: "snmp-exporter"
image_repo: "docker.io/prom"
ver: "v0.30.1"
fw_port:
  - 9116/tcp
  - 116/udp
publish_port:
  - 9116:9116
  - 116:116/udp
command: >
  --config.file=/etc/snmp-exporter/snmp.yml
volume:
  - /opt/{{ app_name }}:/etc/snmp-exporter
