---
- name: Create promtail folder
  ansible.builtin.file:
    path: /opt/promtail
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy promtail config to remote server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/promtail/
    mode: '0644'
  with_fileglob: "*"
  notify: Restart promtail container

- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.homelab.firewall

- name: Run promtail container
  containers.podman.podman_container:
    name: promtail
    image: docker.io/grafana/promtail:{{ ver }}
    state: stopped
    restart_policy: always
    privileged: true
    publish:
      - "9080:9080"
    volume:
      - /opt/promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/etc/promtail/var/log:ro
    command: >
      -client.external-labels=hostname={{ inventory_hostname }}
      -config.file=/etc/promtail/config.yml
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always

- name: Enable container-promtail service
  ansible.builtin.systemd:
    name: container-promtail
    state: started
    enabled: true
    daemon_reload: true