---
app: "{{ env }}-df"
approot: "/opt/{{ app }}/"
builddir: "/tmp/{{ app }}/"
repo: 'git@github.com:eingram23/'
mysql_root: "{{ lookup('hashi_vault', 'secret=secret/mysql/dfprod:root') }}"
mysql_smfprod: "{{ lookup('hashi_vault', 'secret=secret/mysql/dfprod:smfprod') }}"
privkey: "{{ lookup('hashi_vault', 'secret=secret/git/ssh:key') }}"
