---
- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Change user/owner of Plex files to {{ user_account }}
      ansible.builtin.file:
        path: /mnt/pool0/PlexMedia
        state: directory
        owner: "{{ user_account }}"
        group: "{{ user_account }}"
        mode: '0755'
        recurse: true

    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    - name: Create and run container - {{ app_name }}
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ image }}:{{ ver }}"
        state: stopped
        restart_policy: always
        env:
          PUID=0
          PGID=0
          VERSION=docker
          TZ=America/Los_Angeles
        network_mode: host
        device: "/dev/dri:/dev/dri"
        volume:
          - /mnt/pool0/PlexMedia/config:/config:Z
          - /mnt/pool0/PlexMedia/Movies:/movies:Z
          - /mnt/pool0/PlexMedia/3DMovies:/3dmovies:Z
          - /mnt/pool0/PlexMedia/AnimMovies:/animmovies:Z
          - /mnt/pool0/PlexMedia/TVShows:/tvshows:Z
          - /mnt/pool0/PlexMedia/AnimTVShows:/animtvshows:Z
          - /mnt/pool0/PlexMedia/Videos:/videos:Z
        generate_systemd:
          path: "{{ '/home/' + user_account + '/.config/systemd/user' if user_account != 'root' else '/etc/systemd/system' }}"
          restart_policy: always

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd