---
- name: Create and run plex_srv container
  containers.podman.podman_container:
    name: "plex_srv"
    image: lscr.io/linuxserver/docker-plex:{{ plex_srv_ver }}
    state: started
    restart_policy: unless-stopped
    env:
      PUID=1000
      PGID=1000
      VERSION=docker
    network_mode: host
    volume:
      - /opt/plex/config:/config:z
      - /opt/plex/movies:/movies:z
      - /opt/plex/tv:/tv:z