---
- name: Create and run plex_srv container
  containers.podman.podman_container:
    name: "plex_srv"
    image: lscr.io/linuxserver/plex:{{ plex_srv_ver }}
    state: started
    restart_policy: unless-stopped
    env:
      PUID=1000
      PGID=1000
      VERSION=docker
    network_mode: host
    security_opt:
      - label=disable
    volume:
      - /mnt/pool0/PlexMedia/config:/config:Z
      - /mnt/pool0/PlexMedia/Movies:/movies:Z
      - /mnt/pool0/PlexMedia/3DMovies:/3dmovies:Z
      - /mnt/pool0/PlexMedia/AnimMovies:/animmovies:Z
      - /mnt/pool0/PlexMedia/TVShows:/tvshows:Z
      - /mnt/pool0/PlexMedia/AnimTVShows:/animtvshows:Z
      - /mnt/pool0/PlexMedia/Videos:/videos:Z