---
- name: Create and run plex_srv container
  containers.podman.podman_container:
    name: "plex_srv"
    image: lscr.io/linuxserver/docker-plex:{{ plex_srv_ver }}
    state: started
    restart_policy: unless-stopped
    env:
      PUID=1000
      PGID=1000
      VERSION=docker
    network_mode: host
    volume:
      - /mnt/pool0/PlexMedia/config:/config:z
      - /mnt/pool0/PlexMedia/Movies:/movies:z
      - /mnt/pool0/PlexMedia/3DMovies:/3dmovies:z
      - /mnt/pool0/PlexMedia/AnimMovies:/animmovies:z
      - /mnt/pool0/PlexMedia/TVShows:/tvshows:z
      - /mnt/pool0/PlexMedia/AnimTVShows:/animtvshows:z
      - /mnt/pool0/PlexMedia/Videos:/videos:z