---
- name: Create github key
  ansible.builtin.template:
    src: ssh-key-git.key.j2
    dest: /home/poduser/.ssh/ssh-key-git.key
    mode: '0400'

- name: Create site supporting folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    mode: '0755'
  loop:
    - "{{ root }}{{ app }}"
    - "{{ builddir }}"

- name: Clone containers repo from github
  ansible.builtin.git:
    repo: "{{ repo }}containers.git"
    dest: "{{ builddir }}"
    key_file: /home/poduser/.ssh/ssh-key-git.key
    accept_hostkey: true
    clone: true
    update: true

- name: Build wordpress-web image
  containers.podman.podman_image:
    name: "{{ app }}-web"
    path: "{{ builddir }}wordpress"
    force: true

- name: Create app pod
  ansible.builtin.include_role:
    name: eingram23.containers.create_pod
  vars:
    pod_name: "{{ app }}"
    publish_ports:
      - "{{ wp_port }}:80"

- name: Run wordpress-web container
  containers.podman.podman_container:
    name: "{{ app }}-web"
    image: localhost/{{ app }}-web
    env:
      WORDPRESS_DB_HOST: "{{ app }}-db"
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "{{ mysql_wp }}"
      WORDPRESS_DB_NAME: wordpress
    volume:
      - "{{ app }}-web:/var/www/html"
    state: started
    restart_policy: always
    pod: "{{ app }}"

- name: Run wordpress-db container
  containers.podman.podman_container:
    name: "{{ app }}-db"
    image: docker.io/mariadb:{{ mariadb_ver }}
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_wp_root }}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "{{ mysql_wp }}"
    volume:
      - "{{ app }}-data:/var/lib/mysql"
    state: started
    restart_policy: always
    pod: "{{ app }}"

# - name: Remove container clone
#   ansible.builtin.file:
#     path: "{{ builddir }}"
#     state: absent