---
- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Create folder for {{ app_name }}
      ansible.builtin.file:
        path: /opt/{{ app_name }}/plugins
        recurse: true
        state: directory
        mode: '0755'

    - name: Download multiverse-core
      ansible.builtin.get_url:
        url: https://dev.bukkit.org/projects/multiverse-core/files/5901717/download
        dest: /opt/{{ app_name }}/plugins/MultiVerse-Core-4.3.14.jar
        mode: '0644'

    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    - name: Create and run container for {{ app_name }}
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ image }}:{{ ver }}"
        restart_policy: always
        env:
          EULA=TRUE
          TYPE=PAPER
          VERSION={{ ver }}
          MOTD="Paper Minecraft Server powered by Podman"
          SERVER_PORT=25565
          ENABLE_RCON=TRUE
          RCON_PASSWORD={{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}
        tty: true
        interactive: true
        publish: "{{ publish_port }}"
        volume:
          - /opt/{{ app_name }}:/data:z
        state: stopped
        generate_systemd:
          path: "{{ '/home/' + user_account + '/.config/systemd/user' if user_account != 'root' else '/etc/systemd/system' }}"
          restart_policy: always

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd
