---
app_name: "portainer_agent"
image: "docker.io/portainer/agent"
upgrade: "no"
fw_port:
  - "9001/tcp"
mode: "rootful"
portainer_url: "http://portainer.local.lan:9000"
app_port: "9001"
publish_port:
  - "9001:9001"
