---
- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.linux.firewall
    apply:
      become: true
      become_method: sudo
      become_user: root

- name: Prep for upgrade
  when: upgrade == "yes"
  block:
    - name: Stop systemd service for container - {{ app_name }}
      ansible.builtin.systemd:
        name: container-{{ app_name }}
        state: stopped
        scope: user

    - name: Remove container - {{ app_name }}
      containers.podman.podman_container:
        name: "{{ app_name }}"
        state: absent

    - name: Remove image for {{ app_name }}
      containers.podman.podman_image:
        name: lscr.io/linuxserver/plex:latest
        state: absent

- name: Create container - {{ app_name }}
  containers.podman.podman_container:
    name: "{{ app_name }}"
    image: docker.io/nberk/ha_bambu_lab_p1_spaghetti_detection_standalone:{{ obico_ml_ver }}
    state: stopped
    restart_policy: unless-stopped
    env:
      ML_API_TOKEN={{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}
      TZ=America/Los_Angeles
    publish:
      - "3333:3333"
    generate_systemd:
      path: /home/poduser/.config/systemd/user
      restart_policy: always

- name: Set XDG_RUNTIME_DIR env variable
  ansible.builtin.lineinfile:
    path: /home/poduser/.bash_profile
    search_string: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'
    insertafter: '# User specific environment and startup programs'
    line: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'

- name: Get poduser info
  ansible.builtin.user:
    name: poduser
  register: poduser_info

- name: Generate systemd units for container - {{ app_name }}
  containers.podman.podman_generate_systemd:
    name: "{{ app_name }}"
    no_header: true
    restart_policy: always
    dest: ~/.config/systemd/user/

- name: Enable and start service - container-{{ app_name }}
  ansible.builtin.systemd:
    name: container-{{ app_name }}
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ poduser_info.uid }}
