{
 "title": "Energy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Solar Power Production (History)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'envoy_202233021811_current_power_production') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "envoy_202233021811_current_power_production"
      }
     ]
    }
   ]
  },
  {
   "title": "Home Power Consumption (kW)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (\"value\") FROM \"kW\" WHERE (\"entity_id\" = 'home_power_consumption')"
    }
   ]
  },
  {
   "title": "Solar Power Production",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (\"value\") FROM \"W\" WHERE (\"entity_id\" = 'envoy_202233021811_current_power_production')"
    }
   ]
  },
  {
   "title": "Current Power Net/Debt (kW)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (\"value\") FROM \"kW\" WHERE (\"entity_id\" = 'rainforest_emu_2_power')"
    }
   ]
  },
  {
   "title": "Monthly Energy Usage (kWh)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Monthly",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_monthly" }
     ]
    }
   ]
  },
  {
   "title": "Home Power Consumption (History)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT (\"value\") FROM \"kW\" WHERE (\"entity_id\" = 'home_power_consumption')"
    }
   ]
  },
  {
   "title": "Power Net/Debt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "rainforest_emu_2_power" }
     ]
    }
   ]
  },
  {
   "title": "Daily Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Daily",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT mean(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'energy_daily') AND $timeFilter GROUP BY time(24h) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_daily" }
     ]
    }
   ]
  },
  {
   "title": "Monthly Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT last(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'energy_monthly') AND $timeFilter GROUP BY time(1M) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_monthly" }
     ]
    }
   ]
  }
 ]
}