{
 "title": "Unifi Wifi SNMP Overview",
 "description": "Custom Prometheus Unifi Wifi Overview by LTP using SNMP Exporter.",
 "tags": [
  "prometheus",
  "snmp",
  "unifi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "AP Host",
    "query": {
     "query": "label_values(unifiApSystemModel,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AP Interfaces",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "unifiVapBssId{type=\"unifi-wifi\"}"
    }
   ]
  },
  {
   "title": "Network Efficiency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unifiVapRxErrors + unifiVapTxErrors) * 100/ sum(unifiVapRxPackets+unifiVapTxPackets)",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum(unifiVapRxDropped + unifiVapTxDropped) * 100/ sum(unifiVapRxPackets+unifiVapTxPackets)",
     "legendFormat": "Drop Rate"
    },
    {
     "expr": "sum(unifiVapTxRetries) * 100/ sum(unifiVapRxPackets+unifiVapTxPackets)",
     "legendFormat": "Retry Rate"
    }
   ]
  },
  {
   "title": "Connecting Clients by ESSID",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum by(unifiVapEssId) (unifiVapNumStations{hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read/Transfer Traffics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(hostname) (unifiVapRxBytes{hostname=~\"$hostname\"} != 0)",
     "legendFormat": "Rx {{hostname}}"
    },
    {
     "expr": "sum by(hostname) (unifiVapTxBytes{hostname=~\"$hostname\"} != 0)",
     "legendFormat": "Tx {{hostname}}"
    }
   ]
  },
  {
   "title": "Connecting Clients by AP",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hostname) (unifiVapNumStations{hostname=~\"$hostname\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AP Information",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "unifiApSystemModel{hostname=~\"$hostname\"}"
    }
   ]
  }
 ]
}