{
 "title": "UniFi-Poller: Client DPI - Prometheus",
 "description": "UniFi Poller v2.0.1 Displays DPI information for clients in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Controller", "query": "label_values(source)" },
   {
    "name": "Site",
    "query": "label_values(unpoller_client_uptime_seconds{source=~\"$Controller\"},site_name)"
   },
   { "name": "Identifier", "query": "name,mac" },
   {
    "name": "Client",
    "query": "label_values(unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\"},[[Identifier]])"
   },
   {
    "name": "Category",
    "query": "label_values(unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\"},category)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>If this dashboard contains no data that means you need to enable DPI. It must be enabled on your UniFi controller AND in UniFi Poller. Two places! Please carefully check your <a href=\"https://github.com/unifi-poller/unifi-poller/wiki/Configuration\">configurations</a>.</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Totals Category",
   "type": "table",
   "description": "This shows lifetime rx+tx total and totals accumulated during the selected time range. The filters at the top of this page control _all_ of the graphs, and in some cases control the visibility of graphs. ie. Adding more clients displays more graphs under the collapsed Clients rows.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by (site_name, category) (unpoller_client_dpi_receive_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", category=~\"$Category\"})"
    },
    {
     "expr": "sum by (site_name, category) (unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", category=~\"$Category\"})"
    },
    {
     "expr": "sum by (site_name, category) (increase(unpoller_client_dpi_receive_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", category=~\"$Category\"}[$__range]))"
    },
    {
     "expr": "sum by (site_name, category) (increase(unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", category=~\"$Category\"}[$__range]))"
    },
    {
     "expr": "sum by (site_name, category)  (increase(unpoller_client_dpi_receive_packets{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", category=~\"$Category\"}[$__range]))"
    },
    {
     "expr": "sum by (site_name, category)  (increase(unpoller_client_dpi_transmit_packets{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", category=~\"$Category\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Traffic by Category",
   "type": "piechart",
   "description": "Showing traffic by category.\nThis updates with the variables on the dashboard.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category) (increase(unpoller_client_dpi_receive_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=~\"$Category\"}[$__range])+increase(unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=~\"$Category\"}[$__range]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Total Traffic by Application",
   "type": "piechart",
   "description": "Showing traffic by application for selected clients. This updates with the variables on the dashboard.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (category, application) (increase(unpoller_client_dpi_receive_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=~\"$Category\"}[$__range])+increase(unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\",  category=~\"$Category\"}[$__range]))",
     "legendFormat": "{{application}} ({{category}})"
    }
   ]
  },
  {
   "title": "Bytes Transferred per Category",
   "type": "timeseries",
   "description": "Bytes Transferred by Category. Receive is on the negative axis.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (category)(rate(unpoller_client_dpi_receive_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=~\"$Category\"}[$__interval]))",
     "legendFormat": " {{category}} Rx"
    },
    {
     "expr": "sum by (category)(rate(unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\",  category=~\"$Category\"}[$__interval]))",
     "legendFormat": "{{category}} Tx"
    }
   ]
  },
  {
   "title": "Packets Transferred  per Category",
   "type": "timeseries",
   "description": "Packets Transferred by Category. Receive is on the negative axis.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (category)(rate(unpoller_client_dpi_receive_packets{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=~\"$Category\"}[$__interval]))",
     "legendFormat": " {{category}} Rx"
    },
    {
     "expr": "sum by (category)(rate(unpoller_client_dpi_transmit_packets{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=~\"$Category\"}[$__interval]))",
     "legendFormat": "{{category}} Tx"
    }
   ]
  },
  {
   "title": "Clients Rx Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Receive Packets - $Client",
     "type": "graph",
     "description": "Receive Packets per Application for $Client",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
     "repeat": "Client",
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_client_dpi_receive_packets{site_name=~\"$Site\", [[Identifier]]!~\"TOTAL\", [[Identifier]]=~\"$Client\"}[$__interval])",
       "legendFormat": "{{application}} ({{category}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients Tx Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Transmit Bytes - $Client",
     "type": "graph",
     "description": "Transmit Bytes per Application for $Client",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
     "repeat": "Client",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\", [[Identifier]]!~\"TOTAL\", [[Identifier]]=~\"$Client\"}[$__interval])",
       "legendFormat": "{{application}} ({{category}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients Tx Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Transmit Packets - $Client",
     "type": "graph",
     "description": "Transmit Packets per Application for $Client",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "repeat": "Client",
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_client_dpi_transmit_packets{site_name=~\"$Site\", [[Identifier]]!~\"TOTAL\", [[Identifier]]=~\"$Client\"}[$__interval])",
       "legendFormat": "{{application}} ({{category}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients Rx Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Receive Bytes - $Client",
     "type": "graph",
     "description": "Receive Bytes per Application for $Client",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
     "repeat": "Client",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_client_dpi_receive_bytes{site_name=~\"$Site\", [[Identifier]]!~\"TOTAL\", [[Identifier]]=~\"$Client\"}[$__interval])",
       "legendFormat": "{{application}} ({{category}})"
      }
     ]
    }
   ]
  },
  {
   "title": "$Category",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "repeat": "Category",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Receive Bytes - $Category",
     "type": "graph",
     "description": "Receive Bytes per Client / Application",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by ($Identifier,application) (rate(unpoller_client_dpi_receive_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=\"$Category\"}[$__interval]))",
       "legendFormat": "{{name}} {{mac}} ({{application}})"
      }
     ]
    },
    {
     "title": "Transmit Bytes - $Category",
     "type": "graph",
     "description": "Transmit Bytes per Client / Application",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by ($Identifier,application) (rate(unpoller_client_dpi_transmit_bytes{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=\"$Category\"}[$__interval]))",
       "legendFormat": "{{name}} {{mac}} ({{application}})"
      }
     ]
    },
    {
     "title": "Receive Packets - $Category",
     "type": "graph",
     "description": "Receive Packets per Client / Application",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by ($Identifier,application) (rate(unpoller_client_dpi_receive_packets{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=\"$Category\"}[$__interval]))",
       "legendFormat": "{{name}} {{mac}} ({{application}})"
      }
     ]
    },
    {
     "title": "Transmit Packets - $Category",
     "type": "graph",
     "description": "Transmit Packets per Client / Application",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by ($Identifier,application) (rate(unpoller_client_dpi_transmit_packets{site_name=~\"$Site\", [[Identifier]]=~\"$Client\", [[Identifier]]!~\"TOTAL\", category=\"$Category\"}[$__interval]))",
       "legendFormat": "{{name}} {{mac}} ({{application}})"
      }
     ]
    }
   ]
  }
 ]
}