---
- name: Copy servers.json to host
  ansible.builtin.copy:
    src: servers.json
    dest: /home/poduser/pgadmin4/servers.json
    mode: '0644'

- name: Pull pgadmin image and start container
  containers.podman.podman_container:
    name: "{{ pgadmin_container }}"
    image: docker.io/dpage/pgadmin4:6.13
    env:
      PGADMIN_DEFAULT_EMAIL: "edward.ingram23@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/data/ssh/eingram:ssh_password') }}"
    pod: "{{ pod_name }}"
    volume:
      - "{{ pgadmin_container }}-data:/var/lib/pgadmin"
      - "/home/poduser/pgadmin4/servers.json:/pgadmin4/servers.json"
    state: started
    restart_policy: always