---
app: "{{ env }}-ycdisp"
root: '/home/poduser/code/'
repo: 'git@github.com:eingram23/'
smtp_pw: "{{ lookup('hashi_vault', 'secret=secret/google/smtp:password') }}"
mysql_root: "{{ lookup('hashi_vault', 'secret=secret/mysql/ycprod:root') }}"
mysql_yandcprod: "{{ lookup('hashi_vault', 'secret=secret/mysql/ycprod:yandcprod') }}"
privkey: "{{ lookup('hashi_vault', 'secret=secret/git/ssh:key') }}"

