---
- name: Create site supporting folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    mode: '0755'
  loop:
    - "{{ root }}{{ app }}"
    - "{{ builddir }}"

- name: Create github key
  ansible.builtin.template:
    src: ssh-key-git.key.j2
    dest: /home/poduser/.ssh/ssh-key-git.key
    mode: '0400'

# - name: Pause playbook until web files are uploaded to host
#   pause:
#     prompt: "Make sure web file backup is in /home/poduser and renamed to sitebackup.tar.gz"

- name: Clone www.ycdisp.com repo from github
  ansible.builtin.git:
    repo: "{{ repo }}www.ycdisp.com.git"
    dest: "{{ root }}{{ app }}"
    clone: true
    key_file: /home/poduser/.ssh/ssh-key-git.key
    accept_hostkey: true
    update: true
    force: true

- name: Clone Containers repo from github
  ansible.builtin.git:
    repo: "{{ repo }}Containers.git"
    dest: "{{ builddir }}"
    key_file: /home/poduser/.ssh/ssh-key-git.key
    accept_hostkey: true
    clone: true
    update: true

- name: Build ycdisp.com-web image
  containers.podman.podman_image:
    name: "{{ app }}-web"
    path: "{{ builddir }}ycdisp.com/apache"
    force: true
    build:
      extra_args: --build-arg PASSWORD={{ smtp_pw }}

- name: Copy sql backup to build Location
  ansible.builtin.copy:
    src: yandcprod.sql
    dest: "{{ builddir }}ycdisp.com/mariadb"

- name: Build ycdisp.com-db image
  containers.podman.podman_image:
    name: "{{ app }}-db"
    path: "{{ builddir }}ycdisp.com/mariadb"
    force: true

- name: Create ycdisp.com pod
  containers.podman.podman_pod:
    name: "{{ app }}"
    state: started
    publish: "{{ nginx_port }}:80"

- name: Run ycdisp.com-web container
  containers.podman.podman_container:
    name: "{{ app }}-web"
    image: localhost/{{ app }}-web
    volume:
      - "{{ root }}{{ app }}/public_html:/var/www/html:z"
    state: started
    restart_policy: always
    pod: "{{ app }}"

- name: Run ycdisp.com-db container
  containers.podman.podman_container:
    name: "{{ app }}-db"
    image: localhost/{{ app }}-db
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root }}"
      MYSQL_DATABASE: yandcprod
      MYSQL_USER: yandcprod
      MYSQL_PASSWORD: "{{ mysql_yandcprod }}"
    volume:
      - yandctest-data:/var/lib/mysql
    state: started
    restart_policy: always
    pod: "{{ app }}"

- name: Configure connection string
  ansible.builtin.lineinfile:
    path: "{{ root }}{{ app }}/public_html/includes/globals.ini.php"
    search_string: "{{ item.search }}"
    line: "{{ item.replace }}"
  loop:
    - { search: '$database_dbc = "dbname";', replace: '$database_dbc = "yandcprod";' }
    - { search: '$username_dbc = "username";', replace: '$username_dbc = "yandcprod";' }
    - { search: '$password_dbc = "password";', replace: '$password_dbc = "{{ mysql_yandcprod }}";' }

- name: Change site URL to test.ycdisp.com (if env = test)
  ansible.builtin.lineinfile:
    path: "{{ root }}{{ app }}/public_html/includes/globals.ini.php"
    search_string: 'define("siteUrl","http://www.ycdisp.com/");'
    line: 'define("siteUrl","http://test.ycdisp.com/");'
  when: env == "test"

- name: Remove build folder
  ansible.builtin.file:
    path: "{{ builddir }}"
    state: absent
  when: env == "www"