---
- name: Create supporting folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: true
    owner: '2000'
    group: '2000'
  loop:
    - /opt/calibre/config
    - /opt/calibre/books

- name: Run calibre container
  containers.podman.podman_container:
    name: calibre{{ suffix }}
    image: lscr.io/linuxserver/calibre:{{ calibre_ver }}
    state: started
    restart_policy: unless-stopped
    privileged: true
    env:
      VIRTUAL_HOST: "{{ suffix }}libdata.diversionforum.net"
      VIRTUAL_PORT: 8080
      PUID: 2000
      PGID: 2000
      TZ: America/Los_Angeles
    volume:
      - /opt/calibre/config:/config:z

- name: Run calibre-web container
  containers.podman.podman_container:
    name: calibre-web{{ suffix }}
    image: lscr.io/linuxserver/calibre-web:{{ calibre_web_ver }}
    state: started
    restart_policy: unless-stopped
    privileged: true
    env:
      VIRTUAL_HOST: "{{ suffix }}lib.diversionforum.net"
      VIRTUAL_PORT: 8083
      LETSENCRYPT_HOST: "{{ suffix }}lib.diversionforum.net"
      LETSENCRYPT_EMAIL: "edward.ingram23@gmail.com"
      PUID: 2000
      PGID: 2000
      TZ: America/Los_Angeles
      DOCKER_MODS: linuxserver/mods:universal-calibre
    volume:
      - /opt/calibre/config:/config:z
      - /opt/calibre/books:/books
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always

- name: Enable container services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - container-calibre-web{{ suffix }}