---
- name: Create supporting folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: true
    owner: '2000'
    group: '2000'
  loop:
    - /opt/calibre/config
    - /opt/calibre/books

- name: Prep for upgrade
  when: upgrade == "yes"
  block:
    - name: Stop systemd service for calibre containers
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - container-calibre
        - container-calibre-web

    - name: Remove calibre containers
      containers.podman.podman_container:
        name: "{{ item }}"
        state: absent
      loop:
        - calibre
        - calibre-web

- name: Run calibre container
  containers.podman.podman_container:
    name: calibre
    image: lscr.io/linuxserver/calibre:{{ calibre_ver }}
    state: started
    restart_policy: always
    privileged: true
    env:
      VIRTUAL_HOST: "{{ env }}libdata.diversionforum.net"
      VIRTUAL_PORT: 8080
      PUID: 2000
      PGID: 2000
      TZ: America/Los_Angeles
    volume:
      - /opt/calibre/config:/config:z

- name: Run calibre-web container
  containers.podman.podman_container:
    name: calibre-web
    image: lscr.io/linuxserver/calibre-web:{{ calibre_web_ver }}
    state: started
    restart_policy: always
    privileged: true
    env:
      VIRTUAL_HOST: "{{ env }}lib.diversionforum.net"
      VIRTUAL_PORT: 8083
      LETSENCRYPT_HOST: "{{ env }}lib.diversionforum.net"
      LETSENCRYPT_EMAIL: "edward.ingram23@gmail.com"
      PUID: 2000
      PGID: 2000
      TZ: America/Los_Angeles
      DOCKER_MODS: linuxserver/mods:universal-calibre
    volume:
      - /opt/calibre/config:/config:z
      - /opt/calibre/books:/books
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always

- name: Enable container services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - container-calibre
    - container-calibre-web
