---
- name: Pull phpmyadmin image and start container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/phpmyadmin:{{ ver }}
    env:
      PMA_HOST: "{{ mariadb_container_name }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root }}"
      # APACHE_PORT: "8090"
      VIRTUAL_HOST: "{{ app }}phpmyadmin.local.lan"
    pod: "{{ pod_name }}"
    state: started
    restart_policy: always
