---
- name: Pull phpmyadmin image and start container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/phpmyadmin:{{ ver }}
    env:
      PMA_HOST: "{{ mariadb_container_name }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      APACHE_PORT: "{{ phpmyadmin_port }}"
    pod: "{{ pod_name }}"
    state: started
    restart_policy: always
    # network: "{{ podman_network }}"
