---
- name: Pull phpmyadmin image and start container
  containers.podman.podman_container:
    name: phpmyadmin
    image: docker.io/phpmyadmin:5.2.0-apache
    env:
      PMA_HOST: "127.0.0.1"
      PMA_ARBITRARY: "1"
    pod: "{{ pod_name }}"
    state: started
    restart_policy: always