---
- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env_docker

- name: Prep for upgrade
  when: upgrade == "yes"
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: upgrade_docker

- name: Run container (dns + dhcp) - {{ app_name }}
  when: dhcp == "yes"
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: "{{ image }}:{{ ver }}"
    state: started
    restart_policy: always
    network_mode: host
    env:
      DNS_SERVER_DOMAIN: "{{ inventory_hostname }}"
      DNS_SERVER_ADMIN_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    volumes:
      - "{{ app_name }}-data:/etc/dns"
    timeout: 300

- name: Run container (dns) - {{ app_name }}
  when: dhcp == "no"
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: "{{ image }}:{{ ver }}"
    state: started
    restart_policy: always
    published_ports: "{{ publish_port }}"
    env:
      DNS_SERVER_DOMAIN: "{{ inventory_hostname }}"
      DNS_SERVER_ADMIN_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    volumes:
      - "{{ app_name }}-data:/etc/dns"
    sysctls:
      net.ipv4.ip_local_port_range: "1024 65000"
    timeout: 300
