- name: Remove container - {{ app_name }}
  community.docker.docker_container:
    name: "{{ app_name }}"
    state: absent

- name: Cleanup image
  community.docker.docker_image:
    name: "{{ image }}:{{ ver }}"
    state: absent

- name: Remove container - {{ app_name }}
  community.docker.docker_container:
    name: "{{ app_name }}"
    state: absent

- name: Remove volumes for {{ app_name }}
  community.docker.docker_volume:
    name: "{{ app_name }}_data"
    state: absent

- name: Remove volumes for {{ app_name }}
  community.docker.docker_volume:
    name: "portainer_data"
    state: absent
