---
- name: Remove Podman Agent environment from Portainer
  block:
    - name: Login to Portainer API
      ansible.builtin.uri:
        url: "{{ portainer_url }}/api/auth"
        method: POST
        body_format: json
        body:
          username: "admin"
          password: "{{ lookup('hashi_vault', 'secret=secret/portainer:password') }}"
        status_code: 200
      register: auth_response

    - name: Get environment ID for {{ inventory_hostname }} - {{ user_account }}
      ansible.builtin.uri:
        url: "{{ portainer_url }}/api/endpoints"
        method: GET
        headers:
          Authorization: "Bearer {{ auth_response.json.jwt }}"
        status_code: 200
      register: environment_list

    - name: Find environment ID
      ansible.builtin.set_fact:
        agent_environment_id: "{{ item.Id }}"
      loop: "{{ environment_list.json }}"
      when: item.Name == inventory_hostname + ' - ' + user_account

    - name: Remove Podman Agent environment
      ansible.builtin.uri:
        url: "{{ portainer_url }}/api/endpoints/{{ agent_environment_id }}"
        method: DELETE
        headers:
          Authorization: "Bearer {{ auth_response.json.jwt }}"
        status_code: 204
