#! /bin/sh
#
# This script should be called by upssched via the CMDSCRIPT directive.
#
# Here is a quick example to show how to handle a bunch of possible
# timer names with the help of the case structure.
#
# This script may be replaced with another program without harm.
#
# The first argument passed to your CMDSCRIPT is the name of the timer
# from your AT lines.

logger -t upssched-cmd "Calling upssched-cmd $1"

case $1 in
        emailonbatt)
                {
                        echo From: nut.ycdisp.net
                        echo To: edward.ingram23@gmail.com
                        echo Subject: NUT Alert - ONBATTERY
                        echo
                        echo Power loss - Using battery power.
                }  | ssmtp -v edward.ingram23@gmail.com
                ;;
        startshutdown)
                {
                        echo From: nut.ycdisp.net
                        echo To: edward.ingram23@gmail.com
                        echo Subject: NUT Alert - SHUTDOWN STARTING
                        echo
                        echo Shutting down VMs and ESXi hosts
                }  | ssmtp -v edward.ingram23@gmail.com
                /powershell/pwsh /etc/nut/nut_shutdown.ps1
                ;;
        emailonline)
                {
                        echo From: nut.ycdisp.net
                        echo To: edward.ingram23@gmail.com
                        echo Subject: NUT Alert - POWER BACK ONLINE
                        echo
                        echo Power restored
                }  | ssmtp -v edward.ingram23@gmail.com
                ;;
        *)
                logger -t upssched-cmd "Unrecognized command: $1"
                ;;
esac