---
- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Copy blackbox.yml to remote server
      ansible.builtin.copy:
        src: blackbox.yml
        dest: /opt/{{ app_name }}/blackbox.yml
        mode: '0644'
        owner: poduser
        group: poduser

    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    - name: Create and run container for {{ app_name }}
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ image }}:{{ ver }}"
        state: stopped
        restart_policy: always
        publish:
          - "9115:9115"
        command: >
          --config.file=/etc/blackbox/blackbox.yml
        volume:
          - /opt/{{ app_name }}/blackbox.yml:/etc/blackbox/blackbox.yml
        generate_systemd:
          path: /home/{{ user_account }}/.config/systemd/user
          restart_policy: always

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd
