---
app_name: "dns_server"
image: "docker.io/technitium/dns-server"
upgrade: "no"
fw_port:
  - "5380/tcp"
  - "53/tcp"
  - "53/udp"
publish_port:
  - "5380:5380"
  - "{{ ansible_facts['ansible_default_ipv4']['address'] }}:53:53"
  - "{{ ansible_facts['ansible_default_ipv4']['address'] }}:53:53/udp"
