---
app_name: "dns_server"
image: "docker.io/technitium/dns-server"
upgrade: "no"
fw_port:
  - "5380/tcp"
  - "53/tcp"
  - "53/udp"
publish_port:
  - "5380:5380"
  - "53:53"
  - "53:53/udp"
user_account: "root"
