---
- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Enable persistent storage for journalctl
      ansible.builtin.file:
        path: /var/log/journal
        state: directory
        mode: '0644'

    - name: Create config.alloy on remote server
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: /opt/{{ app_name }}/{{ item }}
        mode: '0644'
      loop:
        - config.alloy

    - name: Check if node-exporter or promtail containers exist
      ansible.builtin.include_tasks:
        file: migrate.yaml

    - name: Check if grafana_agent container exists
      containers.podman.podman_container_info:
        name: grafana_agent
      register: grafana_agent_info
      ignore_errors: true

    - name: Remove grafana_agent container if found
      when: grafana_agent_info.containers|length > 0
      ansible.builtin.include_role:
        name: eingram23.containers.grafana_agent
        tasks_from: uninstall

    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    - name: Run container for {{ app_name }}
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ image }}:{{ ver }}"
        state: stopped
        restart_policy: always
        privileged: true
        publish: "{{ publish_port }}"
        cap_add:
          - SYS_TIME
        command: >
          run --server.http.listen-addr=0.0.0.0:12345
          --disable-reporting
          --storage.path=/var/lib/alloy/data
          /etc/alloy/config.alloy
        volume:
          - /:/host/root:ro,rslave
          - /sys:/host/sys:ro,rslave
          - /proc:/host/proc:ro,rslave
          - /var/log:/var/log:ro
          - /opt/{{ app_name }}:/etc/alloy
        generate_systemd:
          path: "{{ '/home/' + user_account + '/.config/systemd/user' if user_account != 'root' else '/etc/systemd/system' }}"
          restart_policy: always

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd
