---
- name: Check if node-exporter container exists
  containers.podman.podman_container_info:
    name: node-exporter
  register: node_exporter_info
  ignore_errors: true
  become: true
  become_method: sudo
  become_user: poduser

- name: Remove node-exporter container if found
  when: node_exporter_info.containers|length > 0
  become: true
  become_method: sudo
  become_user: poduser
  block:
    - name: Stop container-node-exporter
      ansible.builtin.systemd:
        name: container-node-exporter
        state: stopped
        enabled: false
        scope: user

    - name: Remove node-exporter container
      containers.podman.podman_container:
        name: node-exporter
        state: absent

    - name: Remove node-exporter images
      containers.podman.podman_image:
        name: "{{ item.Image }}"
        state: absent
      loop: "{{ node_exporter_info.containers }}"

- name: Check if promtail container exists
  containers.podman.podman_container_info:
    name: promtail
  register: promtail_info
  ignore_errors: true

- name: Remove promtail container if found
  when: promtail_info.containers|length > 0
  block:
    - name: Stop container-promtail
      ansible.builtin.systemd:
        name: container-promtail
        state: stopped
        enabled: false

    - name: Remove promtail container
      containers.podman.podman_container:
        name: promtail
        state: absent

    - name: Remove promtail images
      containers.podman.podman_image:
        name: "{{ item.Image }}"
        state: absent
      loop: "{{ promtail_info.containers }}"
