- name: Stop systemd service for {{ app_name }} container
  ansible.builtin.systemd:
    name: container-{{ app_name }}
    state: stopped

- name: Remove {{ app_name }} container
  containers.podman.podman_container:
    name: "{{ app_name }}"
    state: absent

- name: Cleanup image
  containers.podman.podman_image:
    name: "{{ image }}:{{ ver }}"
    state: absent

- name: Remove {{ app_name }} container
  containers.podman.podman_container:
    name: "{{ app_name }}"
    state: absent

- name: Disable container-{{ app_name }} service
  ansible.builtin.systemd:
    name: container-{{ app_name }}
    state: stopped
    enabled: false
    daemon_reload: true

- name: Delete firewall rules
  ansible.builtin.include_role:
    name: eingram23.linux.firewall
    tasks_from: delete
