---
- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Create alertmanager.yml on remote server
      ansible.builtin.template:
        src: alertmanager.yml.j2
        dest: /opt/{{ app_name }}/alertmanager.yml
        mode: '0644'
        owner: "{{ user_account }}"
        group: "{{ user_account }}"

    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    - name: Create and run container - {{ app_name }}
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ image }}:{{ ver }}"
        state: stopped
        restart_policy: always
        publish:
          - "9093:9093"
        command: >
          --config.file=/etc/alertmanager/alertmanager.yml
          --storage.path=/alertmanager
          --web.external-url=http://{{ inventory_hostname }}:9093
        volume:
          - "{{ app_name }}-data:/alertmanager"
          - /opt/{{ app_name }}/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        generate_systemd:
          path: /home/{{ user_account }}/.config/systemd/user
          restart_policy: always

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd
