---
- name: Assert that app and bucket are set
  ansible.builtin.assert:
    that:
      - app is defined
      - port is defined
    fail_msg: "app and port (3306+) are required"

- name: Set app_name
  ansible.builtin.set_fact:
    app_name: "{{ app }}-{{ app_suffix }}"

- name: Set fw_port
  ansible.builtin.set_fact:
    fw_port:
      - "{{ port }}/tcp"
    publish_port:
      - "{{ port }}:3306"

- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    - name: Pull mariadb image and start container
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ image }}:{{ ver }}"
        env:
          MYSQL_ROOT_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
        volume:
          - "{{ app_name }}-data:/var/lib/mysql"
        state: stopped
        restart_policy: always
        publish: "{{ publish_port }}"
        generate_systemd:
          path: "{{ '/home/' + user_account + '/.config/systemd/user' if user_account != 'root' else '/etc/systemd/system' }}"
          restart_policy: always

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd
