---
- name: Pull mariadb image and start container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/mariadb:{{ ver }}
    env:
      MYSQL_ROOT_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    pod: "{{ pod_name }}"
    volume:
      - "{{ container_name }}-data:/var/lib/mysql"
    state: started
    restart_policy: always