- name: Create pod
  containers.podman.podman_pod:
    name: "{{ pod_name }}"
    state: started
    publish: "{{ publish_ports }}"
    generate_systemd:
      path: /home/poduser/systemd
      restart_policy: always
      