---
- name: Open firewall port
  ansible.builtin.include_role:
    name: eingram23.linux.firewall

- name: Make sure podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Install podman-plugins
  ansible.builtin.package:
    name: podman-plugins
    state: present

- name: Prep for upgrade
  when: upgrade == "yes"
  block:
    - name: Stop systemd service for {{ app_name }} container
      ansible.builtin.systemd:
        name: container-{{ app_name }}
        state: stopped

    - name: Remove {{ app_name }} container
      containers.podman.podman_container:
        name: "{{ app_name }}"
        state: absent

- name: Run {{ app_name }} container
  containers.podman.podman_container:
    name: "{{ app_name }}"
    image: "{{ image }}:{{ ver }}"
    state: stopped
    restart_policy: always
    privileged: true
    user: root
    publish:
      - "9633:9633"
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always

- name: Enable container-{{ app_name }} service
  ansible.builtin.systemd:
    name: container-{{ app_name }}
    state: started
    enabled: true
    daemon_reload: true
