server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://podhost1.local.lan:3100/loki/api/v1/push

scrape_configs:
- job_name: messages
  static_configs:
  - targets:
      - localhost
    labels:
      job: messages
      __path__: /etc/promtail/var/log/messages

- job_name: secure
  static_configs:
  - targets:
      - localhost
    labels:
      job: secure
      __path__: /etc/promtail/var/log/secure

- job_name: cron
  static_configs:
  - targets:
      - localhost
    labels:
      job: cron
      __path__: /etc/promtail/var/log/cron
