---
- name: Create .smbpasswd file
  become: true
  become_method: sudo
  ansible.builtin.copy:
    dest: "/home/poduser/.smbpasswd"
    content: |
      username={{cifs_user}}
      password={{cifs_pwd}}
    mode: '0600'

- name: Mount //homenas.local.lan/Shared
  become: true
  become_method: sudo
  ansible.posix.mount:
    src: //homenas.local.lan/Shared
    path: /mnt/Shared
    opts: rw,credentials=/home/poduser/.smbpasswd,file_mode=0776,dir_mode=0777
    state: mounted
    fstype: cifs
