---
app_name: "unifi"
user_account: "poduser"
upgrade: "no"
fw_port:
  - "3478/udp"
  - "10001/udp"
  - "8080/tcp"
  - "8443/tcp"
  - "1900/udp"
  - "8843/tcp"
  - "8880/tcp"
  - "6789/tcp"
  - "5514/tcp"
