---
- name: Modify html perms to make updates possible
  ansible.builtin.file:
    path: "{{root}}{{app}}/public_html"
    state: directory
    recurse: yes
    mode: '0777'
  
- name: Pause playbook until updates are finished
  pause:
    prompt: "Hit enter when updates are finished"
