---
# - name: Create supporting folder structure
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: directory
#     owner: poduser
#     group: poduser
#     mode: 0775
#   loop:
#     - "{{ root }}{{ app }}"
#     - /home/poduser/.config/systemd/user

- name: Set nginx port (www)
  ansible.builtin.set_fact:
    nginx_port: 8081
  when: env == "www"

- name: Set nginx port (test)
  ansible.builtin.set_fact:
    nginx_port: 8082
  when: env == "test"

- name: Check if dfsitebackup.tar.gz exists
  ansible.builtin.stat:
    path: /home/poduser/dfsitebackup.tar.gz
  register: dfsitebackup

- name: Stop playbook if dfsitebackup.tar.gz doesn't exist
  ansible.builtin.fail:
    msg: "dfsitebackup.tar.gz not found"
  when: not dfsitebackup.stat.exists

- name: Check if dfsqlbackup.bak.gz exists
  ansible.builtin.stat:
    path: /home/poduser/dfsqlbackup.bak.gz
  register: dfsqlbackup

- name: Stop playbook if dfsqlbackup.bak.gz doesn't exist
  ansible.builtin.fail:
    msg: "dfsqlbackup.bak.gz not found"
  when: not dfsqlbackup.stat.exists

- name: Create github key
  ansible.builtin.template:
    src: ssh-key-git.key.j2
    dest: /home/poduser/.ssh/ssh-key-git.key
    mode: '0400'

- name: Create site root folder
  ansible.builtin.file:
    path: "{{ root }}{{ app }}"
    state: directory
    mode: '0755'
  register: siteroot

- name: Extract web files to html root
  ansible.builtin.unarchive:
    src: /home/poduser/dfsitebackup.tar.gz
    dest: "{{ root }}{{ app }}/"
    remote_src: true
    extra_opts: [--strip-components=4]
  when: not siteroot.stat.exists

- name: Add db password to Settings.php
  ansible.builtin.lineinfile:
    path: "{{ root }}{{ app }}/public_html/Settings.php"
    search_string: '$db_passwd = '
    line: $db_passwd = '{{ mysql_smfprod }}';

- name: Copy repair_settings.php
  ansible.builtin.copy:
    src: repair_settings.php
    dest: "{{ root }}{{ app }}/public_html/repair_settings.php"

- name: Set perms on webfiles
  ansible.builtin.shell:
    cmd: |
      find {{ root }}{{ app }}/public_html -type d -exec chmod 0755 {} \;
      find {{ root }}{{ app }}/public_html -type f -exec chmod 0644 {} \;
      podman unshare chown -R 33:33 {{ root }}{{ app }}/public_html/

- name: Clone Containers repo from github
  ansible.builtin.git:
    repo: "{{ repo }}Containers.git"
    dest: "{{ root }}Containers"
    key_file: /home/poduser/.ssh/ssh-key-git.key
    accept_hostkey: true
    clone: true
    update: true

- name: Build diversionforum.net-web image
  containers.podman.podman_image:
    name: "{{ app }}-nginx"
    path: "{{ root }}Containers/{{ app }}/nginx"
    force: true

- name: Build diversionforum.net-php image
  containers.podman.podman_image:
    name: "{{ app }}-php"
    path: "{{ root }}Containers/{{ app }}/php"
    force: true

- name: Extract df sql backup
  ansible.builtin.shell: gunzip -c /home/poduser/dfsqlbackup.bak.gz > {{ root }}Containers/{{ app }}/mariadb/smfprod.sql

- name: Build diversionforum.net-mariadb image
  containers.podman.podman_image:
    name: "{{ app }}-mariadb"
    path: "{{ root }}Containers/{{ app }}/mariadb"
    force: true

- name: Create diversionforum.net pod
  containers.podman.podman_pod:
    name: "{{ app }}"
    state: started
    publish: "{{ nginx_port }}:{{ nginx_port }}"

- name: Run diversionforum.net-web container
  containers.podman.podman_container:
    name: "{{ app }}-nginx"
    image: localhost/{{ app }}-nginx
    volume:
      - "{{ root }}{{ app }}/public_html:/var/www/html:z"
    state: started
    restart_policy: always
    pod: "{{ app }}"

- name: Run diversionforum.net-php container
  containers.podman.podman_container:
    name: "{{ app }}-php"
    image: localhost/{{ app }}-php
    volume:
      - "{{ root }}{{ app }}/public_html:/var/www/html"
    state: started
    restart_policy: always
    pod: "{{ app }}"

- name: Run diversionforum.net-mariadb container
  containers.podman.podman_container:
    name: "{{ app }}-mariadb"
    image: localhost/{{ app }}-mariadb
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root }}"
      MYSQL_DATABASE: smfprod
      MYSQL_USER: smfprod
      MYSQL_PASSWORD: "{{ mysql_smfprod }}"
    volume:
      - smf{{ env }}-data:/var/lib/mysql
    state: started
    restart_policy: always
    pod: "{{ app }}"
