- name: Create vault container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/hashicorp/vault:"{{ ver }}"
    state: started
    restart_policy: always
    pod: "{{ pod_name }}"
    env:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    cap_add:
      - IPC_LOCK
