---
- name: Set base website permissions
  ansible.builtin.file:
    dest: "{{root}}{{app}}/public_html"
    mode: u=rwX,g=rX,o=rX
    recurse: true

- name: Make Settings.php writable
  ansible.builtin.file:
    dest: "{{root}}{{app}}/public_html/{{ item }}"
    mode: u=rwX,g=rwX,o=rwX
  loop:
    - Settings.php
    - Settings_bak.php

- name: Modify html perms to make necessary folders writable
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    recurse: yes
    mode: u=rwX,g=rwX,o=rwX
    owner: poduser
    group: poduser
  loop:
    - "{{root}}{{app}}/public_html/attachments"
    - "{{root}}{{app}}/public_html/attachmentsPreREI"
    - "{{root}}{{app}}/public_html/avatars"
    - "{{root}}{{app}}/public_html/custom_avatar"
    - "{{root}}{{app}}/public_html/cache"
    - "{{root}}{{app}}/public_html/exports"
    - "{{root}}{{app}}/public_html/Packages"
    - "{{root}}{{app}}/public_html/Smileys"
    - "{{root}}{{app}}/public_html/Themes"
    - "{{root}}{{app}}/public_html/profile_pictures"