---
- name: Create loki folder
  ansible.builtin.file:
    path: /opt/loki
    state: directory
    mode: '0755'
    owner: poduser
    group: poduser
  become: true
  become_method: sudo
  become_user: root

- name: Run podman unshare
  ansible.builtin.shell:
    podman unshare chown -R 0:0 /opt/loki

- name: Copy loki config file to remote server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/loki/
    mode: '0644'
    owner: poduser
    group: poduser
  with_fileglob: "*"
  notify: Restart loki container

- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.homelab.firewall
    apply:
      become: true
      become_method: sudo
      become_user: root

- name: Run podman unshare
  ansible.builtin.shell:
    podman unshare chown -R 10001:10001 /opt/loki

- name: Create and run loki container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/grafana/loki:{{ ver }}
    state: started
    restart_policy: always
    pod: "{{ pod_name }}"
    command: >
      -config.file=/etc/loki/loki-config.yaml
    volume:
      - /opt/loki/loki-config.yaml:/etc/loki/loki-config.yaml

