---
- name: Create supporting folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: true
    owner: poduser
    group: poduser
  loop:
    - /opt/node-exporter
  become: true
  become_method: sudo
  become_user: root

- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.homelab.firewall
    apply:
      become: true
      become_method: sudo
      become_user: root

- name: Copy files to host
  ansible.builtin.copy:
    src: web-config.yml
    dest: /opt/node-exporter
    mode: '0644'
    owner: poduser
    group: poduser

- name: Create tls.crt on host
  ansible.builtin.template:
    src: tls.crt.j2
    dest: /opt/node-exporter/tls.crt
    mode: '440'
    owner: poduser
    group: poduser

- name: Create tls.key on host
  ansible.builtin.template:
    src: tls.key.j2
    dest: /opt/node-exporter/tls.key
    mode: '400'
    owner: poduser
    group: poduser

- name: Run podman unshare
  ansible.builtin.shell:
    podman unshare chown -R 65534:65534 /opt/node-exporter

- name: Run node-exporter container
  containers.podman.podman_container:
    name: node-exporter
    image: docker.io/prom/node-exporter:{{ ver }}
    state: started
    restart_policy: unless-stopped
    privileged: true
    network: host
    pid: host
    command: >
      --path.rootfs=/host
      --web.config.file=web-config.yml
    volume:
      - /:/host:ro,rslave
      - /opt/node-exporter:/etc/node-exporter
    # generate_systemd:
    #   path: /etc/systemd/system
    #   restart_policy: always