---
- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env_docker

- name: Prep for upgrade
  when: upgrade == "yes"
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: upgrade_docker

- name: Create container for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_container_docker
