---
- name: Install podman-remote, podman-docker
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - podman-remote
    - podman-docker

- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.homelab.firewall

- name: Create supporting folder
  ansible.builtin.file:
    path: /opt/nginx-proxy
    state: directory
    mode: '0755'

- name: Copy proxy.conf to host
  ansible.builtin.copy:
    src: proxy.conf
    dest: /opt/nginx-proxy
    mode: '0644'

- name: Enable/start podman.socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true

- name: Prep for upgrade
  when: upgrade == "yes"
  block:
    - name: Stop systemd service for nginx-proxy containers
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - container-nginx-proxy
        - container-nginx-proxy-acme

    - name: Remove nginx-proxy containers
      containers.podman.podman_container:
        name: "{{ item }}"
        state: absent
      loop:
        - container-nginx-proxy
        - container-nginx-proxy-acme

- name: Run nginx container
  containers.podman.podman_container:
    name: nginx-proxy
    image: docker.io/nginxproxy/nginx-proxy:{{ nginx_proxy_ver }}
    state: started
    restart_policy: always
    publish:
      - "80:80"
      - "443:443"
    privileged: true
    volume:
      - certs:/etc/nginx/certs:z
      - vhost:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /opt/nginx-proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro,z
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always

- name: Run acme-companion container
  containers.podman.podman_container:
    name: nginx-proxy-acme
    image: docker.io/nginxproxy/acme-companion:{{ acme_ver }}
    state: started
    restart_policy: always
    env:
      DEFAULT_EMAIL: edward.ingram23@gmail.com
    privileged: true
    volumes_from:
      - nginx-proxy
    volume:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: always

- name: Enable container-nginx-proxy-acme service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - container-nginx-proxy
    - container-nginx-proxy-acme
