---
- name: Install podman-remote
  ansible.builtin.package:
    name: podman-remote
    state: present
  become: true
  become_method: sudo
  become_user: root

- name: Enable/start podman.socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true
    scope: user

- name: Getent passwd
  ansible.builtin.getent:
    database: passwd

- ansible.builtin.setup:
  register: facts

- ansible.builtin.debug:
    var: facts
    
- name: Run nginx container
  containers.podman.podman_container:
    name: nginx-proxy
    image: docker.io/nginxproxy/nginx-proxy:{{ nginx_proxy_ver }}
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    volume:
      - certs:/etc/nginx/certs:z
      - vhost:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /run/user/{{ getent_passwd[ ansible_become_user ].2 }}/podman/podman.sock:/tmp/docker.sock:z

- name: Run acme-companion container
  containers.podman.podman_container:
    name: nginx-proxy-acme
    image: docker.io/nginxproxy/acme-companion:{{ acme_ver }}
    state: started
    restart_policy: unless-stopped
    env:
      DEFAULT_EMAIL: edward.ingram23@gmail.com
    volume:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh