---
- name: Install podman-remote, podman-docker
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - podman-remote
    - podman-docker

- name: Enable/start podman.socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true

# - name: Create nginx-proxy pod
#   ansible.builtin.include_role:
#     name: eingram23.containers.create_pod

- name: Run nginx container
  containers.podman.podman_container:
    name: nginx-proxy
    image: docker.io/nginxproxy/nginx-proxy:{{ nginx_proxy_ver }}
    state: started
    restart_policy: unless-stopped
    # pod: "{{ pod_name }}"
    privileged: true
    volume:
      - certs:/etc/nginx/certs:z
      - vhost:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:ro,z

# - name: Run acme-companion container
#   containers.podman.podman_container:
#     name: nginx-proxy-acme
#     image: docker.io/nginxproxy/acme-companion:{{ acme_ver }}
#     state: started
#     restart_policy: unless-stopped
#     pod: "{{ pod_name }}"
#     env:
#       DEFAULT_EMAIL: edward.ingram23@gmail.com
#     privileged: true
#     volumes_from:
#       - nginx-proxy
#     volume:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - acme:/etc/acme.sh