---
- name: Deploy www.ycdisp.com
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: no
  become_user: poduser
  become_method: sudo

  vars:
    app: "www.ycdisp.com"
    container: "www.ycdisp.com"
    root: '/home/poduser/code/'
    repo: 'git@github.com:eingram23/'
    smtp_pw: "{{ lookup('hashi_vault','secret=secret/data/google/smtp:password') }}"
    mysql_root: "{{ lookup('hashi_vault','secret=secret/data/ycprod/mysql:root') }}"
    mysql_yandcprod: "{{ lookup('hashi_vault','secret=secret/data/ycprod/mysql:yandcprod') }}"
    nginx_port: "8081"

  roles:
    - common

  