---

- name: Copy backup script to server
  ansible.builtin.copy:
    src: unifi_backup.py
    dest: "/home/poduser/unifi_backup.py"
    mode: '0755'

- name: Create cron backup job
  ansible.builtin.cron:
    name: "Backup unifi-controller data"
    hour: "2"
    job: "/usr/bin/python3 /home/poduser/unifi_backup.py"

- name: Mount NAS share
  include_role:
    name: mount_nas