---
- name: Create prometheus folder
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    mode: '0755'
    owner: poduser
    group: poduser
  become: true
  become_method: sudo
  become_user: root

- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.homelab.firewall
    apply:
      become: true
      become_method: sudo
      become_user: root


- name: Copy prometheus files to remote server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/prometheus/
    mode: '0644'
    owner: poduser
    group: poduser
  with_fileglob: "*"

- name: Create and run prometheus container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/prom/prometheus:{{ ver }}
    state: started
    restart_policy: always
    pod: "{{ pod_name }}"
    # cmd_args:
    #   - "--web.external-url=http://{{ inventory_hostname }}:9091"
    volume:
      - "{{ container_name }}-data:/prometheus"
      - /opt/prometheus/:/etc/prometheus/

- name: Copy prometheus files to remote server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/prometheus/
    mode: '0644'
    owner: poduser
    group: poduser
  with_fileglob: "*"
  tags:
    - never
    - update_prometheus
  notify: Restart prometheus container