---
- name: Copy prometheus.yml to remote server
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
    mode: '0644'
    owner: poduser
    group: poduser

- name: Create and run prometheus container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: prom/prometheus:{{ ver }}
    state: started
    restart_policy: always
    pod: "{{ pod_name }}"
    volume:
      - "{{ container_name }}-data:/prometheus"
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
