app: "{{ env }}-df"
root: '/home/poduser/code/'
builddir: '/home/poduser/build/'
repo: 'git@github.com:eingram23/'
podman_network: "webapps"
mysql_root: "{{ lookup('hashi_vault', 'secret=secret/mysql/dfprod:root') }}"
mysql_smfprod: "{{ lookup('hashi_vault', 'secret=secret/mysql/dfprod:smfprod') }}"
privkey: "{{ lookup('hashi_vault', 'secret=secret/git/ssh:key') }}"
