- debug: var=volumes

- name: Create and run container - {{ app_name }}
  containers.podman.podman_container:
    name: "{{ app_name }}"
    image: "{{ image }}:{{ ver }}"
    state: stopped
    restart_policy: always
    privileged: "{{ privileged }}"
    publish: "{{ publish_port }}"
    volume: "{{ volumes | default(omit) }}"
    device: "{{ devices | default(omit) }}"
    command: "{{ container_command | default(omit) }}"
    generate_systemd:
      path: "{{ '/home/' + user_account + '/.config/systemd/user' if user_account != 'root' else '/etc/systemd/system' }}"
      restart_policy: always
