- name: Run root tasks
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  block:
    - name: Check if user_account exists
      ansible.builtin.getent:
        database: passwd
        key: "{{ user_account }}"
      register: user_exists

    - name: Fail if user_account does not exist
      ansible.builtin.fail:
        msg: "The user_account {{ user_account }} does not exist on this system."
      when: user_exists is not defined

    - name: Ensure podman is installed
      ansible.builtin.package:
        name: "{{ podman_items }}"
        state: present
      loop:
        - podman
        - podman-compose
        - podman-plugins
        - podman-remote
      loop_control:
        loop_var: podman_items

    - name: Enable linger for user {{ user_account }}
      when: user_account != "root"
      ansible.builtin.command: loginctl enable-linger {{ user_account }}
      args:
        creates: /var/lib/systemd/linger/{{ user_account }}

    - name: Set default logging driver to journald if rootless
      ansible.builtin.copy:
        src: containers.conf
        dest: "{{ ansible_env.HOME }}/.config/containers/containers.conf"
        owner: "{{ user_account }}"
        group: "{{ user_account }}"
        mode: '0644'
      when: user_account != "root"

    - name: Open firewall port
      when: fw_port is defined
      ansible.builtin.include_role:
        name: eingram23.linux.firewall

    - name: Create folder for {{ app_name }}
      ansible.builtin.file:
        path: /opt/{{ app_name }}
        state: directory
        mode: '0755'
        owner: "{{ user_account }}"
        group: "{{ user_account }}"
