- name: Enable root service - container-{{ app_name }}
  when: user_account == 'root'
  ansible.builtin.systemd:
    name: container-{{ app_name }}
    state: started
    enabled: true
    daemon_reload: true

- name: Enable user service - container-{{ app_name }}
  when: user_account != 'root'
  block:
    - name: Set XDG_RUNTIME_DIR env variable
      ansible.builtin.lineinfile:
        path: /home/{{ user_account }}/.bash_profile
        search_string: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'
        insertafter: '# User specific environment and startup programs'
        line: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'

    - name: Get info for {{ user_account }}
      ansible.builtin.user:
        name: "{{ user_account }}"
      register: user_info

    - name: Enable service - container-{{ app_name }}
      ansible.builtin.systemd:
        name: container-{{ app_name }}
        state: started
        enabled: true
        daemon_reload: true
        scope: user
      environment:
        XDG_RUNTIME_DIR: /run/user/{{ user_info.uid }}
