- name: Run root tasks
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  block:
    - name: Close firewall ports
      when: fw_port is defined
      ansible.builtin.include_role:
        name: eingram23.linux.firewall
        tasks_from: delete

    - name: Remove folder for {{ app_name }}
      ansible.builtin.file:
        path: /opt/{{ app_name }}
        state: absent

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Get container info for {{ app_name }}
      containers.podman.podman_container_info:
        name: "{{ app_name }}"
      register: app_info
      ignore_errors: true

    - name: Remove container if found - {{ app_name }}
      when: app_info.containers | length > 0
      block:
        - name: Stop systemd service for container - {{ app_name }}
          ansible.builtin.systemd:
            name: container-{{ app_name }}
            state: stopped
            scope: "{{ 'user' if user_account != 'root' else omit }}"

        - name: Remove container - {{ app_name }}
          containers.podman.podman_container:
            name: "{{ app_name }}"
            state: absent

        - name: Remove images for {{ app_name }}
          containers.podman.podman_image:
            name: "{{ image_item.Image }}"
            state: absent
          loop: "{{ app_info.containers }}"
          loop_control:
            loop_var: image_item

        - name: Delete all volumes for {{ app_name }}
          when: app_info.containers[0].Mounts | length > 0
          containers.podman.podman_volume:
            name: "{{ vol_item.Name }}"
            state: absent
          loop: "{{ app_info.containers[0].Mounts | selectattr('Name', 'defined') | list }}"
          loop_control:
            loop_var: vol_item

        - name: Disable service - container-{{ app_name }}
          ansible.builtin.systemd:
            name: container-{{ app_name }}
            state: stopped
            scope: "{{ 'user' if user_account != 'root' else omit }}"
            enabled: false
            daemon_reload: true
