---
- name: Set rootless vars
  when: user_account != "root"
  block:
    - name: Get user info for {{ user_account }}
      ansible.builtin.getent:
        database: passwd
        key: "{{ user_account }}"

    - name: Get user id for {{ user_account }}
      ansible.builtin.set_fact:
        uid: "{{ getent_passwd[user_account][1] }}"

    - name: Obtain new port for accessing app
      ansible.builtin.set_fact:
        app_port: "{{ ((uid | int) + 7080) | string }}"

    - name: Set new ports for app
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
      loop:
        - { key: 'fw_port', value: ["{{ app_port }}/tcp"] }

- name: Uninstall {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: remove_all
