---
- name: Mount NAS share
  include_role:
    name: mount_nas

- name: Prompt to copy backup to localhost
  ansible.posix.synchronize:
    src: /mnt/Shared/Backup/Containers/unifi-controller/{{backup_filename}}
    dest: /home/poduser/{{backup_filename}}  
  delegate_to: "{{ inventory_hostname }}"

- name: Stop unifi-controller container
  containers.podman.podman_container:
    name: unifi-controller
    state: stopped

- name: Restore unifi-controller data
  ansible.builtin.command: podman run --volumes-from unifi-controller --privileged --rm -v /home/poduser:/backup busybox sh -c "cd /config && tar xzvf /backup/{{backup_filename}} --strip 1"

- name: Start unifi-controller container
  containers.podman.podman_container:
    name: unifi-controller
    state: started