- name: Create build folder
  ansible.builtin.file:
    path: "/opt/{{ app_name }}/build"
    state: directory

- name: Clone containers repo from github
  ansible.builtin.git:
    repo: "{{ repo }}containers.git"
    dest: "/opt/{{ app_name }}/build"
    clone: true
    update: true

# - name: Create build dir
#   ansible.builtin.file:
#     path: "{{ builddir }}{{ app }}"
#     state: directory

# - name: Copy nut-pwsh-upsd container out to build dir
#   ansible.builtin.copy:
#     src: "{{ root }}temp-containers/{{ app }}/"
#     dest: "{{ builddir }}{{ app }}"
#     remote_src: true

- name: Create config files on host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/opt/{{ app_name }}/build/{{ app_name }}/{{ item }}"
    mode: '0600'
  loop:
    - ssmtp.conf

- name: Build nut-pwsh-upsd image
  community.docker.docker_image:
    name: "{{ app }}"
    build:
      path: "/opt/{{ app_name }}/build/{{ app_name }}/"
    source: build

- name: Remove build dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/opt/{{ app_name }}/build/"

