---
- name: Create nut-pwsh-upsd conf folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/{{ app }}

- name: Create shutdown script on host
  ansible.builtin.template:
    src: nut_shutdown.yaml.j2
    dest: /opt/{{ app }}/nut_shutdown.ps1
    mode: '0644'

- name: Copy upssched-cmd to host
  ansible.builtin.copy:
    src: upssched-cmd
    dest: /opt/{{ app }}/upssched-cmd
    mode: '0644'

- name: Start nut-pwsh-upsd container
  community.docker.docker_container:
    name: "{{ app }}"
    image: "{{ app }}:{{ nut_pwsh_upsd_ver }}"
    env:
      API_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    ports:
      - "3493:3493/tcp"
    volumes:
      - /opt/{{ app }}/upssched-cmd:/usr/bin/upssched-cmd
      - /opt/{{ app }}/nut_shutdown.ps1:/etc/nut/nut_shutdown.ps1
    privileged: true
    restart_policy: always

- name: Start nut-exporter container
  community.docker.docker_container:
    name: nut-exporter
    image: docker.io/druggeri/nut_exporter:{{ nut_exporter_ver }}
    env:
      NUT_EXPORTER_SERVER: "dietpi1.local.lan"
      NUT_EXPORTER_VARIABLES: "{{ nut_exporter_vars | join(',') }}"
    ports:
      - "9199:9199/tcp"
    restart_policy: always