---
- name: Create nut-upsd conf folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/nut-upsd

- name: Copy shutdown script to host
  ansible.builtin.copy:
    src: shutdown.yaml
    dest: /opt/nut-upsd/shutdown.yaml
    mode: '0644'

- name: Copy upssched-cmd to host
  ansible.builtin.copy:
    src: upssched-cmd
    dest: /opt/nut-upsd/upssched-cmd
    mode: '0644'

- name: Start homelab-nut-upsd container
  community.docker.docker_container:
    name: "{{ app }}"
    image: "{{ app }}:{{ homelab_nut_upsd_ver }}"
    env:
      API_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    ports:
      - "3493:3493/tcp"
    volumes:
      - /opt/nut-upsd/upssched-cmd:/usr/bin/upssched-cmd
      - /opt/nut-upsd/shutdown.yaml:/etc/nut/shutdown.yaml
    privileged: true
    restart_policy: always

- name: Start nut-exporter container
  community.docker.docker_container:
    name: nut-exporter
    image: docker.io/druggeri/nut_exporter:{{ nut_exporter_ver }}
    env:
      NUT_EXPORTER_SERVER: "dietpi1.local.lan"
      NUT_EXPORTER_VARIABLES: "{{ nut_exporter_vars | join(',') }}"
    ports:
      - "9199:9199/tcp"
    restart_policy: always