---
- name: Check that port is not in use
  when: task == "install"
  ansible.builtin.shell: |
    ss -tuln | grep ':{{ port }}'
  register: fw_port_check
  changed_when: false
  ignore_errors: true

- name: Assert that app and port are defined and port is open
  ansible.builtin.assert:
    that:
      - app is defined
      - port is defined
      - fw_port_check.rc | default(1) == 1
    fail_msg: "app and port (5432+) are required and port must be open"

- name: Set app_name
  ansible.builtin.set_fact:
    app_name: "{{ app }}-{{ app_suffix }}"

- name: Set fw_port
  ansible.builtin.set_fact:
    fw_port:
      - "{{ port }}/tcp"
    publish_port:
      - "{{ port }}:5432"

- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    # - name: Run container - {{ app_name }}
    #   containers.podman.podman_container:
    #     name: "{{ app_name }}"
    #     image: "{{ image }}:{{ ver }}"
    #     env:
    #       POSTGRES_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    #     volume:
    #       - "{{ app_name }}-data:/var/lib/postgresql/data"
    #     state: stopped
    #     restart_policy: always
    #     publish: "{{ publish_port }}"
    #     generate_systemd:
    #       path: "{{ '/home/' + user_account + '/.config/systemd/user' if user_account != 'root' else '/etc/systemd/system' }}"
    #       restart_policy: always

    - name: Create container for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: create_container

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd
