---
- name: Assert that needed vars are set
  ansible.builtin.assert:
    that:
      - app_name is defined
      - pg_port is defined

- name: Set fw_port
  ansible.builtin.set_fact:
    fw_port:
      - "{{ pg_port }}/tcp"
    publish_port:
      - "{{ pg_port }}:5432"

- name: Install env for {{ app_name }}
  ansible.builtin.include_role:
    name: eingram23.containers.common
    tasks_from: create_env

- name: Run tasks as {{ user_account }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ user_account }}"
  block:
    - name: Prep for upgrade
      when: upgrade == "yes"
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: upgrade

    - name: Run container - {{ app_name }}
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ image }}:{{ ver }}"
        env:
          POSTGRES_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
        volume:
          - "{{ app_name }}-data:/var/lib/postgresql/data"
        state: stopped
        restart_policy: always
        publish: "{{ publish_port }}"
        generate_systemd:
          path: "{{ '/home/' + user_account + '/.config/systemd/user' if user_account != 'root' else '/etc/systemd/system' }}"
          restart_policy: always

    - name: Enable service for {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.common
        tasks_from: enable_sysd
