---
- name: Pull postgres image and start postgres container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/postgres:{{ ver }}
    env:
      POSTGRES_PASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
    pod: "{{ pod_name }}"
    volume:
      - "{{ container_name }}-data:/var/lib/postgresql/data"
    state: started
    restart_policy: always