---
- name: Deploy cAdvisor container
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: true

  tasks:   
    - name: Deploy cAdvisor for Redhat/Rocky
      when: ansible_distribution in ['Redhat', 'Rocky']
      ansible.builtin.import_role:
        name: eingram23.containers.cadvisor
        tasks_from: "{{ task }}"

    - name: Deploy cAdvisor for Debian/Ubuntu
      become: true
      when: ansible_distribution in ['Debian', 'Ubuntu']
      ansible.builtin.import_role:
        name: eingram23.containers.cadvisor_docker
        tasks_from: "{{ task }}"