---
# Usage: ansible-playbook container_app.yaml -e "hostvar=host app_name=app task=install user_account=user"

- name: Deploy container app
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: false

  vars_files:
    - "vars/{{ app_name }}.yaml"

  tasks:

    - name: Assert user_account is defined
      ansible.builtin.assert:
        that:
          - user_account is defined
        fail_msg: |
          "The variable 'user_account' must be defined."
          "If this is a monitoring container (e.g., cadvisor), specify which user account to install under."
        success_msg: "The variable 'user_account' is properly defined."

    - name: Assert vars
      ansible.builtin.assert:
        that:
          - app_name is defined
          - task is defined
          - task in ['install', 'uninstall', 'upgrade']
        fail_msg: |
          "The variables 'app_name', 'user_account', and 'task' must be defined."
          "The 'task' variable must be set to either 'install', 'uninstall', or 'upgrade'."
        success_msg: "All required variables are properly defined."

    - name: Manage container app - {{ app_name }}
      ansible.builtin.include_role:
        name: eingram23.containers.container_app
        tasks_from: "{{ task }}"
