---
- name: Deploy minecraft paper server container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: false

  tasks:

    - ansible.builtin.import_role:
        name: eingram23.containers.minecraft
        tasks_from: "{{ task }}"
