---
- name: Deploy obico_ml container
  hosts: "{{ hostvar | default('homenas.local.lan') }}"
  gather_facts: false
  become: false

  tasks:

    - name: Run obico_ml role
      ansible.builtin.import_role:
        name: eingram23.containers.obico_ml_ha
        tasks_from: "{{ task }}"
