---
- name: Deploy plex_srv container
  hosts: "{{ hostvar | default('homenas.local.lan') }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: shareaccess

  tasks:

    - name: Assert task and user_account are defined
      ansible.builtin.assert:
        that:
          - task is defined
          - task in ['install', 'uninstall']
          - user_account is defined
        fail_msg: "The 'task' variable must be defined and set to either 'install' or 'uninstall'."
        success_msg: "The 'task' variable is defined and valid."
        
    - name: Deploy plex_srv container
      ansible.builtin.include_role:
        name: eingram23.containers.plex_srv
        tasks_from: "{{ task }}"
