---
- name: Deploy portainer_agent container
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: true

  tasks:   
    - name: Deploy portainer agent for Redhat/Rocky
      when: ansible_distribution in ['Redhat', 'Rocky']
      ansible.builtin.import_role:
        name: eingram23.containers.portainer_agent
        tasks_from: "{{ task }}"

    - name: Deploy portainer agent for Debian/Ubuntu
      become: true
      when: ansible_distribution in ['Debian', 'Ubuntu']
      ansible.builtin.import_role:
        name: eingram23.containers.portainer_agent_docker
        tasks_from: "{{ task }}"