---
# NEEDED VARS: hostvar
- name: Deploy promtail
  hosts: "{{ hostvar | default([]) }}"
  become: false

  tasks:

    - name: Assert task and user_account are defined
      ansible.builtin.assert:
        that:
          - task is defined
          - task in ['install', 'uninstall']
          - user_account is defined
        fail_msg: "The 'task' variable must be defined and set to either 'install' or 'uninstall'."
        success_msg: "The 'task' variable is defined and valid."
        
    - name: Deploy promtail_syslog container
      ansible.builtin.import_role:
        name: eingram23.containers.promtail_syslog
        tasks_from: "{{ task }}"
