---
- name: Deploy rancher container
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: true

  tasks:   
    - name: Deploy rancher for Redhat/Rocky
      when: ansible_distribution in ['Redhat', 'Rocky']
      ansible.builtin.import_role:
        name: eingram23.containers.rancher
        tasks_from: "{{ task }}"

    # - name: Deploy rancher for Debian/Ubuntu
    #   become: true
    #   when: ansible_distribution in ['Debian', 'Ubuntu']
    #   ansible.builtin.import_role:
    #     name: eingram23.containers.rancher_docker
    #     tasks_from: "{{ task }}"