---
# NEEDED VARS: hostvar
- name: Deploy smartctl_exporter
  hosts: "{{ hostvar | default([]) }}"
  become: true
  become_method: sudo
  gather_facts: false

  tasks:

    - name: Assert task and user_account are defined
      ansible.builtin.assert:
        that:
          - task is defined
          - task in ['install', 'uninstall']
          - user_account is defined
          - user_account == 'root'
        fail_msg: "The 'task' variable must be defined and set to either 'install' or 'uninstall'."
        success_msg: "The 'task' variable is defined and valid."

    - name: Deploy smartctl_exporter container
      ansible.builtin.import_role:
        name: eingram23.containers.smartctl_exporter
        tasks_from: "{{ task }}"
