---
- name: Deploy snmp_exporter container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: false

  tasks:

    - name: Run snmp_exporter role
      ansible.builtin.import_role:
        name: eingram23.containers.snmp_exporter
        tasks_from: "{{ task }}"
