---
- name: Deploy technitium_dns_server container
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: true

  tasks:

    - name: Assert task and user_account are defined
      ansible.builtin.assert:
        that:
          - task is defined
          - task in ['install', 'uninstall']
          - user_account is defined
        fail_msg: "The 'task' variable must be defined and set to either 'install' or 'uninstall'."
        success_msg: "The 'task' variable is defined and valid."
        
    - name: Deploy technitium_dns_server - {{ task }}
      when: ansible_distribution in ['Debian', 'Ubuntu']
      become: true
      become_method: sudo
      ansible.builtin.import_role:
        name: eingram23.containers.technitium_dns_server_docker
        tasks_from: "{{ task }}"

    - name: Deploy technitium_dns_server - {{ task }}
      when: ansible_distribution in ['Redhat', 'Rocky']
      ansible.builtin.import_role:
        name: eingram23.containers.technitium_dns_server
        tasks_from: "{{ task }}"