---
- name: Deploy technitium_dns_server container
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: true

  tasks:

    - name: Deploy technitium_dns_server - {{ task }}
      when: ansible_distribution in ['Debian', 'Ubuntu']
      become: true
      become_method: sudo
      ansible.builtin.import_role:
        name: eingram23.containers.technitium_dns_server_docker
        tasks_from: "{{ task }}"

    - name: Deploy technitium_dns_server - {{ task }}
      when: ansible_distribution in ['Redhat', 'Rocky']
      ansible.builtin.import_role:
        name: eingram23.containers.technitium_dns_server
        tasks_from: "{{ task }}"