---
- name: Deploy unifi-controller
  hosts: "{{ hostvar | default('homenas.local.lan') }}"
  gather_facts: false
  become: false
  tasks:

    - name: Run unifi controller role
      ansible.builtin.import_role:
        name: eingram23.containers.unifi
        tasks_from: "{{ task }}"
