---
- name: Deploy unpoller container for Unifi monitoring
  hosts: "{{ hostvar | default([]) }}"
  become: false

  tasks:

    - name: Deploy unpoller container
      ansible.builtin.import_role:
        name: eingram23.containers.unpoller
        tasks_from: "{{ task }}"
