---
- name: Deploy vault container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy vault container
      ansible.builtin.import_role:
        name: eingram23.containers.vault
        tasks_from: "{{ task }}"
