---
- name: Create root dir for bind mount
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/pihole/etc-pihole
    - /opt/pihole/etc-dnsmasq.d

- name: Copy 05-custom.conf
  ansible.builtin.copy:
    src: 05-custom.conf
    dest: /opt/pihole/etc-dnsmasq.d/05-custom.conf
    mode: '0644'

- name: Start docker container
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:{{ ver }}
    env:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
      DNSMASQ_LISTENING: all
    volumes:
      - /opt/pihole/etc-pihole:/etc/pihole
      - /opt/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart_policy: always
