---
- name: Create root dir for bind mount
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/pihole/etc-pihole
    - /opt/pihole/etc-dnsmasq.d

- name: Create github key
  ansible.builtin.template:
    src: ssh-key-git.key.j2
    dest: /var/tmp/ssh-key-git.key
    mode: '0400'
  delegate_to: localhost

- name: Pull down custom.list from git
  ansible.builtin.git:
    repo: 'git@github.com:eingram23/configs.git'
    dest: /var/tmp
    key_file: /var/tmp/ssh-key-git.key
    accept_hostkey: true
  delegate_to: localhost

- name: Copy custom.list
  ansible.builtin.copy:
    src: /var/tmp/pihole/custom.list
    dest: /opt/pihole/etc-pihole/custom.list
    mode: '0644'

- name: Copy 05-custom.conf
  ansible.builtin.copy:
    src: 05-custom.conf
    dest: /opt/pihole/etc-dnsmasq.d/05-custom.conf
    mode: '0644'

- name: Start docker container
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:{{ ver }}
    env:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: "{{ lookup('hashi_vault', 'secret=secret/data/ssh/eingram:ssh_password') }}"
      DNSMASQ_LISTENING: all
    volumes:
      - /opt/pihole/etc-pihole:/etc/pihole
      - /opt/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart_policy: always

- name: Clean up tmp files
  ansible.builtin.file:
    path: /var/tmp/pihole
    state: absent
  delegate_to: localhost

- name: Clean up key
  ansible.builtin.file:
    path: /var/tmp/ssh-key-git.key
    state: absent
  delegate_to: localhost