---
# old_ver: "v0.49.1"
ver: "v0.49.2"
container_command:
  - --podman=unix:///var/run/podman/podman.sock
  - --docker=unix://
  - --store_container_labels=true
  - --docker_only=true
  - --disable_root_cgroup_stats=true
volumes:
  - /:/rootfs:ro
  - /dev/disk/:/dev/disk:ro
  - /sys:/sys:ro
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /etc/machine-id:/etc/machine-id:ro
  - "{{ '/var/run:/var/run:ro' if user_account == 'root'
    else '/var/run/user/' + uid + ':/var/run:ro' }}"
  - "{{ '/var/lib/containers:/var/lib/containers:ro' if user_account == 'root'
    else '/home/' + user_account + '/.local/share/containers/storage:/var/lib/containers:ro' }}"
privileged: true
devices:
  - /dev/kmsg
