- name: Open firewall ports
  ansible.builtin.include_role:
    name: eingram23.homelab.firewall
    apply:
      become: true
      become_method: sudo
      become_user: root

- name: Create and run vmware_exporter container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: pryorda/vmware_exporter:{{ ver }}
    state: started
    restart_policy: always
    pod: "{{ pod_name }}"
    env:
      VSPHERE_HOST: vcsa-1.local.lan
      VSPHERE_IGNORE_SSL: True
      VSPHERE_USER: "{{ lookup('hashi_vault','secret=secret/vsphere/vcsa:vsphere_username') }}"
      VSPHERE_PASSWORD: "{{ lookup('hashi_vault','secret=secret/vsphere/vcsa:vsphere_password') }}"
