- name: Create and run vmware_exporter container
  containers.podman.podman_container:
    name: vmware_exporter
    image: pryorda/vmware_exporter:v0.18.3
    state: started
    restart_policy: always
    pod: graf_prom_vm
    env:
      VSPHERE_HOST: vcsa.local.lan
      VSPHERE_IGNORE_SSL: True
      VSPHERE_USER: administrator@vsphere.local
      VSPHERE_PASSWORD: "{{ vsphere_pass }}"
