---
- name: UPGRADE - Remove existing container
  when: upgrade == "yes"
  block:
    - name: Stop octoprint container
      community.docker.docker_container:
        name: octoprint
        state: stopped

    - name: Stop octoprint container
      community.docker.docker_container:
        name: octoprint
        state: absent

- name: Create octoprint container
  community.docker.docker_container:
    name: octoprint
    image: octoprint/octoprint:{{ ver }}
    env:
      CAMERA_DEV: '/dev/video0'
      MJPG_STREAMER_INPUT: '-y -n -r 320x240'
      ENABLE_MJPG_STREAMER: 'true'
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - octoprint:/octoprint
    ports:
      - "8080:80/tcp"
    restart_policy: always
